### PR TITLE
Fixes #1020 - Gen.choose() weighted not using seed

### LINKED ISSUE #1020: Gen.choose() Weighted Not Using Seed
`Gen.choose()` weighted version is not using seed value passed to `random()`.

### PR DESCRIPTION
**Pull request by EarthCitizen**

### CODE REVIEW

**Comment by EarthCitizen** [comment]
@Kerooker these test failures do not appear to be because of my change. I ran `./gradlew check` locally on master branch and I get the same errors as in the Travis log.

This fix is blocking me on a PR for the `Gen.char()` effort.

**Comment by LeoColman** [comment]
There was a test which would fail on every first day of a month, I think we derped on it's implementation. I'm fixing it on master now

**Comment by LeoColman** [comment]
#1023

**Comment by LeoColman** [comment]
Please rebase from master

**Comment by EarthCitizen** [comment]
@Kerooker Merged in your changes from master. Green now.

**Comment by LeoColman** [comment]
Nice one, @EarthCitizen!

Thanks for this contribution!

**Pull request merged**
