### PR TITLE
updated FloatShrinker and DoubleShrinker to regard mantissa bit count…

### PR DESCRIPTION
**Pull request by sielenk-yara**
… as complexity measure

This is patch for #2378.

It does not realize a simplification base 10, though.

### CODE REVIEW

**Comment by sksamuel** [comment]
Great stuff, thanks for fixing.

**Comment by sielenk** [comment]
You're welcome (this is also me, sielenk-yara is my company account).

You do realize that this does _not_ what is mentioned in #2378, though?
I am still thinking about getting it done platform-independently in base 10  but this is not yet it.

That said, I do think this is an improvement over the old shrinker which was kind of all over the place - but that is the task of the `Arb`!

**Comment by sksamuel** [comment]
yes I think this is fine for a JVM solution.  I will include this in 4.6.2

**Comment by sielenk** [comment]
This works on all platforms, not just JVM!

**Comment by sksamuel** [comment]
Then I'm just getting confused going over all the outstanding messages lol
:)

**Pull request merged**
