### PR TITLE
Add Array overloads to collection matchers

### LINKED ISSUE #900: Our collection matchers don't work on arrays

### PR DESCRIPTION
**Pull request by LeoColman**
Closes #900

### CODE REVIEW

**Comment by LeoColman** [comment]
What I did here was to exactly duplicate all the matchers, but change them to Array<T>. I also added some overloads in which the parameter type was Collection to suppor Array as well.

**Comment by LeoColman** [comment]
One thing I didn't do was add overloads to all primitive array types, such as `ByteArray` or `IntArray`. There would be too many overloads if i did this.

It can be done if we want tho

**Review by sksamuel — APPROVED** [review]

**Comment by LeoColman** [comment]
I don't think we need documentation for this, right? One can use the collections documentation

**Comment by sksamuel** [comment]
Yeah. Can mention they work.

**Pull request merged**
