### PR TITLE
Native thread local fix

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Review by ajalt — COMMENTED** [review]
This should solve the problem.

A grep turns up a couple more mutable globals in common code:

- io.kotest.property.PropertyTesting
- io.kotest.core.spec.style.scopes.DslState
- io.kotest.assertions.BasicErrorCollector
- io.kotest.core.config.Project

I don't know if those globals are actually mutated.

**Comment by sksamuel** [comment]
DslState and Project are only used by the framework which isn't available in native builds.
BasicErrorCollector will have the same issue so I'll apply the same fix.

**Review by ajalt — APPROVED** [review]
With these changes, Clikt's test suite passes on mingwX64, so this LGTM

**Comment by sksamuel** [comment]
Did you try with my 2nd commit or the first?

**Comment by ajalt** [comment]
> 
> 
> Did you try with my 2nd commit or the first?

The second commit.

**Pull request merged**
