### PR TITLE
Makes properties field mandatory for shouldBeEqualToUsingFields and shouldBeEqualToIgnoringFields

### PR DESCRIPTION
**Pull request by ashishkujoy**

### CODE REVIEW

**Comment by ashishkujoy** [comment]
As of now I cannot think of any shorter and meaning full name for ```shouldBeEqualToIgnoringFields``` and ```shouldBeEqualToUsingFields```. One option is ```shouldHaveEqualFields``` but that does not implies that user need to mention fields which are to use while doing equality check.

Any suggestions for alias @Kerooker @sksamuel

**Comment by sksamuel** [comment]
shouldEqualUsingFields ?

But it's hardly any shorter.

**Comment by ashishkujoy** [comment]
> shouldEqualUsingFields ? But it's hardly any shorter.

Without Be that sounds little off.

**Comment by sksamuel** [comment]
Agreed.

**Pull request merged**
