### PR TITLE
Fixed spec lifecycle ordering for JS

### LINKED ISSUE #3340: Lifecycle hook invocations differ between platforms (Js/JVM)
Kotest 5.5.4, Kotlin 1.7.20

Initial discussion on [slack-chats.kotlinlang.org](https://slack-chats.kotlinlang.org/t/8444671/I-m-trying-to-decipher-how-AbstractProjectConfig-works-in-Ko).

Considering the following lifecycle hooks:
1. PROJECT_CONFIG – `AbstractProjectConfig.{before,after}Project`
2. PROJECT – `ProjectExtension.interceptProject`
3. SPEC – `SpecExtension.intercept`
4. TEST_CASE – `TestCaseExtension.intercept`

On the JVM, the order of invocation is
* Entering PROJECT, PROJECT_CONFIG, SPEC, 
* Entering TEST_CASE, Test execution, Exiting TEST_CASE 
* Exiting SPEC, PROJECT_CONFIG, PROJECT  

On Js, the order of invocation is
* Entering PROJECT, PROJECT_CONFIG, SPEC,
* Exiting SPEC, PROJECT_CONFIG, PROJECT
* Entering TEST_CASE, Test execution, Exiting TEST_CASE

To reproduce: https://github.com/OliverO2/kotest-issue-lifecycle-hooks

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #3340

### CODE REVIEW

**Comment by OliverO2** [comment]
I have extended your test so that it will additionally cover an extension configured project-wide and case-specific (the latter configured differently, intended to override the project-wide setting) . This currently fails on the Jvm, as the case-specific extension will wrap the project-level extension.

Here's the modified code for `LifecycleOrderTest.kt`:
```kotlin
package com.sksamuel.kotest.engine

import io.kotest.core.extensions.ProjectExtension
import io.kotest.core.extensions.SpecExtension
import io.kotest.core.extensions.TestCaseExtension
import io.kotest.core.project.ProjectContext
import io.kotest.core.spec.Spec
import io.kotest.core.spec.style.FunSpec
import io.kotest.core.test.TestCase
import io.kotest.core.test.TestResult
import io.kotest.engine.TestEngineLauncher
import io.kotest.engine.listener.CollectingTestEngineListener
import io.kotest.matchers.shouldBe

class LifecycleOrderTest : FunSpec() {
   init {

      test("project, spec and test interceptors should wrap each other") {
         val collector = CollectingTestEngineListener()
         TestEngineLauncher(collector)
            .withClasses(LifecycleTests::class)
            .withExtensions(LifecycleExtension("project"))
            .launch()
         collector.names shouldBe listOf("foo", "bar")
         LifecycleExtension.state shouldBe listOf(
            Triple("project", Lifecycle.PROJECT, Phase.ENTRY),
            Triple("project", Lifecycle.SPEC, Phase.ENTRY),
            Triple("project", Lifecycle.TEST_CASE, Phase.ENTRY),
            Triple("project", Lifecycle.TEST_CASE, Phase.EXIT),
            Triple("project", Lifecycle.TEST_CASE, Phase.ENTRY),
            Triple("bar", Lifecycle.TEST_CASE, Phase.ENTRY),
            Triple("bar", Lifecycle.TEST_CASE, Phase.EXIT),
            Triple("project", Lifecycle.TEST_CASE, Phase.EXIT),
            Triple("project", Lifecycle.SPEC, Phase.EXIT),
            Triple("project", Lifecycle.PROJECT, Phase.EXIT),
         )
      }
   }
}

private class LifecycleTests : FunSpec() {
   init {
      test("foo") {}
      test("bar").config(extensions = listOf(LifecycleExtension("bar"))) {}
   }
}

enum class Lifecycle {
   PROJECT,
   SPEC,
   TEST_CASE
}

enum class Phase {
   ENTRY,
   EXIT
}

class LifecycleExtension(val name: String) : ProjectExtension, SpecExtension, TestCaseExtension {

   companion object {
      val state = mutableListOf<Triple<String, Lifecycle, Phase>>()
   }

   override suspend fun interceptProject(context: ProjectContext, callback: suspend (ProjectContext) -> Unit) {
      state.add(Triple(name, Lifecycle.PROJECT, Phase.ENTRY))
      callback(context)
      state.add(Triple(name, Lifecycle.PROJECT, Phase.EXIT))
   }

   override suspend fun intercept(spec: Spec, execute: suspend (Spec) -> Unit) {
      state.add(Triple(name, Lifecycle.SPEC, Phase.ENTRY))
      execute(spec)
      state.add(Triple(name, Lifecycle.SPEC, Phase.EXIT))
   }

   override suspend fun intercept(testCase: TestCase, execute: suspend (TestCase) -> TestResult): TestResult {
      state.add(Triple(name, Lifecycle.TEST_CASE, Phase.ENTRY))
      val result = execute(testCase)
      state.add(Triple(name, Lifecycle.TEST_CASE, Phase.EXIT))
      return result
   }
}
```

This produces:
```
Element differ at index: [4, 5, 6, 7]
expected:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (project, TEST_CASE, ENTRY), (bar, TEST_CASE, ENTRY), (bar, TEST_CASE, EXIT), (project, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]> but was:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]>
```

**Comment by sksamuel** [comment]
> I have extended your test so that it will additionally cover an extension configured project-wide and case-specific (the latter configured differently, intended to override the project-wide setting) . This currently fails on the Jvm, as the case-specific extension will wrap the project-level extension.
> 
> Here's the modified code for `LifecycleOrderTest.kt`:
> 
> ```kotlin
> package com.sksamuel.kotest.engine
> 
> import io.kotest.core.extensions.ProjectExtension
> import io.kotest.core.extensions.SpecExtension
> import io.kotest.core.extensions.TestCaseExtension
> import io.kotest.core.project.ProjectContext
> import io.kotest.core.spec.Spec
> import io.kotest.core.spec.style.FunSpec
> import io.kotest.core.test.TestCase
> import io.kotest.core.test.TestResult
> import io.kotest.engine.TestEngineLauncher
> import io.kotest.engine.listener.CollectingTestEngineListener
> import io.kotest.matchers.shouldBe
> 
> class LifecycleOrderTest : FunSpec() {
>    init {
> 
>       test("project, spec and test interceptors should wrap each other") {
>          val collector = CollectingTestEngineListener()
>          TestEngineLauncher(collector)
>             .withClasses(LifecycleTests::class)
>             .withExtensions(LifecycleExtension("project"))
>             .launch()
>          collector.names shouldBe listOf("foo", "bar")
>          LifecycleExtension.state shouldBe listOf(
>             Triple("project", Lifecycle.PROJECT, Phase.ENTRY),
>             Triple("project", Lifecycle.SPEC, Phase.ENTRY),
>             Triple("project", Lifecycle.TEST_CASE, Phase.ENTRY),
>             Triple("project", Lifecycle.TEST_CASE, Phase.EXIT),
>             Triple("project", Lifecycle.TEST_CASE, Phase.ENTRY),
>             Triple("bar", Lifecycle.TEST_CASE, Phase.ENTRY),
>             Triple("bar", Lifecycle.TEST_CASE, Phase.EXIT),
>             Triple("project", Lifecycle.TEST_CASE, Phase.EXIT),
>             Triple("project", Lifecycle.SPEC, Phase.EXIT),
>             Triple("project", Lifecycle.PROJECT, Phase.EXIT),
>          )
>       }
>    }
> }
> 
> private class LifecycleTests : FunSpec() {
>    init {
>       test("foo") {}
>       test("bar").config(extensions = listOf(LifecycleExtension("bar"))) {}
>    }
> }
> 
> enum class Lifecycle {
>    PROJECT,
>    SPEC,
>    TEST_CASE
> }
> 
> enum class Phase {
>    ENTRY,
>    EXIT
> }
> 
> class LifecycleExtension(val name: String) : ProjectExtension, SpecExtension, TestCaseExtension {
> 
>    companion object {
>       val state = mutableListOf<Triple<String, Lifecycle, Phase>>()
>    }
> 
>    override suspend fun interceptProject(context: ProjectContext, callback: suspend (ProjectContext) -> Unit) {
>       state.add(Triple(name, Lifecycle.PROJECT, Phase.ENTRY))
>       callback(context)
>       state.add(Triple(name, Lifecycle.PROJECT, Phase.EXIT))
>    }
> 
>    override suspend fun intercept(spec: Spec, execute: suspend (Spec) -> Unit) {
>       state.add(Triple(name, Lifecycle.SPEC, Phase.ENTRY))
>       execute(spec)
>       state.add(Triple(name, Lifecycle.SPEC, Phase.EXIT))
>    }
> 
>    override suspend fun intercept(testCase: TestCase, execute: suspend (TestCase) -> TestResult): TestResult {
>       state.add(Triple(name, Lifecycle.TEST_CASE, Phase.ENTRY))
>       val result = execute(testCase)
>       state.add(Triple(name, Lifecycle.TEST_CASE, Phase.EXIT))
>       return result
>    }
> }
> ```
> 
> This produces:
> 
> ```
> Element differ at index: [4, 5, 6, 7]
> expected:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (project, TEST_CASE, ENTRY), (bar, TEST_CASE, ENTRY), (bar, TEST_CASE, EXIT), (project, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]> but was:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]>
> ```

Can you confirm that this does actually pass on the JVM because I can't get it to fail.

**Comment by OliverO2** [comment]
> Can you confirm that this does actually pass on the JVM because I can't get it to fail.

Took master as of commit c043f6930abb305c08120360fd053bc209ba62d1 (plus ["Refactor concurrency" PR](https://github.com/kotest/kotest/pull/3623)), ran `LifecycleOrderTest` on JVM -> passed.

Then reverted the change of `TestExtensions.kt` from commit cfc45be3494fec8068c360fd2570d5cb300a9bc1, ran `LifecycleOrderTest` on JVM -> failed:

```
Element differ at index: [4, 5, 6, 7]
expected:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (project, TEST_CASE, ENTRY), (bar, TEST_CASE, ENTRY), (bar, TEST_CASE, EXIT), (project, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]> but was:<[(project, PROJECT, ENTRY), (project, SPEC, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, ENTRY), (project, TEST_CASE, ENTRY), (project, TEST_CASE, EXIT), (bar, TEST_CASE, EXIT), (project, SPEC, EXIT), (project, PROJECT, EXIT)]>
```

**Comment by sksamuel** [comment]
Ok great so my changes to the test executor ended up fixing his too (on JVM).

**Pull request closed without merging**
