### PR TITLE
Clean up unresolved KDoc references

### LINKED ISSUE #4356: Fix the many unresolved KDoc references
There are currently 151 unresolved links in KDoc comments across the whole codebase due to missing imports.
Effect: The rendered links appear clickable, but don't go anywhere.

image

### PR DESCRIPTION
**Pull request by okarmazin**
Closes #4356 

There were a few typos, but most cases were solved by adding the appropriate import. I also ran the autoformatter on the changed files, so there may be the occasional whitespace adjustment or import reordering as well.

In two cases there were leftover Java references in the common source set. I replaced these with an appropriate Kotlin variant - examples referencing IOException/FileNotFoundException were replaced with IllegalArgumentException/NumberFormatException with preserved meaning.

This PR reduces the number of unresolved references from about 60 to 11. Of these 11 at least 2 symbols no longer exist (see #4357), with others I was unsure about what symbol is supposed to be referenced.

### CODE REVIEW

**Review by LeoColman — APPROVED** [review]
Cool

**Comment by AlexCue987** [comment]
very nice. feel free to share the ones you weren't sure about, maybe open an issue?

**Review by AlexCue987 — APPROVED** [review]

**Comment by okarmazin** [comment]
Looks like a flaky runner

**Comment by okarmazin** [comment]
The failing test: https://github.com/kotest/kotest/blob/5f94d7ffd924dd049829363bf12c6a06ee4cc9c8/kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/CollectionsTest.kt#L101

https://scans.gradle.com/s/gon2c2rcmbz6k/tests/task/:kotest-property:jvmMaxJdkTest/details/com.sksamuel.kotest.property.arbitrary.CollectionsTest/maintain%20performance%20fixed%20by%20https:%2F%2Fgithub.com%2Fkotest%2Fkotest%2Fissues%2F4016?top-execution=1

It hits the timeout on the macos runner, unrelated to this PR.

**Comment by AlexCue987** [comment]
> The failing test:
> 
> https://github.com/kotest/kotest/blob/5f94d7ffd924dd049829363bf12c6a06ee4cc9c8/kotest-property/src/jvmTest/kotlin/com/sksamuel/kotest/property/arbitrary/CollectionsTest.kt#L101
> 
> https://scans.gradle.com/s/gon2c2rcmbz6k/tests/task/:kotest-property:jvmMaxJdkTest/details/com.sksamuel.kotest.property.arbitrary.CollectionsTest/maintain%20performance%20fixed%20by%20https:%2F%2Fgithub.com%2Fkotest%2Fkotest%2Fissues%2F4016?top-execution=1
> 
> It hits the timeout on the macos runner, unrelated to this PR.

yeah, that's unrelated

**Pull request merged**
