### PR TITLE
#1418 Depreciate `isolation` in favor of new `isolationMode` parameter for inline test configuration

### PR DESCRIPTION
**Pull request by BrianOdisho**
Resolves issue #1418

### CODE REVIEW

**Comment by sksamuel** [comment]
Thanks for the PR. Can't merge while the build is red. @Kerooker the reason I called it isolation and not isolationMode is because the latter then clashes with the fun isolationMode() in the parent.

You might need to do some trickery to get it to work.

**Comment by crazyk2** [comment]
How about tests and docs?

**Comment by BrianOdisho** [comment]
> Thanks for the PR. Can't merge while the build is red. @Kerooker the reason I called it isolation and not isolationMode is because the latter then clashes with the fun isolationMode() in the parent.
> 
> You might need to do some trickery to get it to work.

Thanks for the additional context @sksamuel ! I’ll look into this more today.

**Comment by sksamuel** [comment]
Since I don't think we can reuse isolationMode because of the function I vote we close this and stick with the status quo.

**Comment by BrianOdisho** [comment]
Agreed I’m not seeing a way to resolve this without a breaking change to the api.

**Pull request closed without merging**
