### PR TITLE
#970 Adds a sentence generator

### PR DESCRIPTION
**Pull request by ashishkujoy**

### CODE REVIEW

**Comment by EarthCitizen** [comment]
I would move the tests to its own module called `GenSentenceTest`. This will help organize the tests.

**Comment by EarthCitizen** [comment]
Can you give some examples of intended output? Is the intention of this to generate valid sentences? If so, it does not look like it will. The reason why I ask is because it looks like it will, with some constraints, basically generate the same output as what a bunch of random strings joined by spaces would be.

**Comment by sksamuel** [comment]
qeqwe oisdo 128asd mkkjco qwieu

is a valid sentence in my eyes.

**Comment by sksamuel** [comment]
Or if you want to get cleverer could use lorem ipsum

**Comment by EarthCitizen** [comment]
It just seems that the result is about the same as generated strings with spaces included. If we are not concerned about the content of the sentence, I thin the same thing can be achieved with existing functions, even if we do add a `Gen.sentence()`. For example:

```kotlin
val space = Gen.from(listOf(' '))
val lower = Gen.from(('a'..'z').toList())
val upper = Gen.from(('A'..'Z').toList())
val nums = Gen.from(('0'..'9').toList())
Gen.choose(
  1 to space,
  20 to lower,
  20 to upper,
  10 to nums
).take(500)
```
This could be even simpler once `Gen.char()` is flushed out and merged.

**Comment by sksamuel** [comment]
Yeah I think that's fine. It's just a useful gen to have to basically
generated strings with spaces.

**Comment by EarthCitizen** [comment]
Yeah for sure. We just need to be sure that we are using existing building blocks and not re-inventing the wheel, so to speak.

@ashishkujoy What I gave is not intended to be exactly what is required. Just pointing out what we can build upon existing functionality.

**Comment by EarthCitizen** [comment]
@ashishkujoy Another option (and probably better), would be something like this:

```kotlin
val lower = Gen.from(('a'..'z').toList())
val upper = Gen.from(('A'..'Z').toList())
val nums = Gen.from(('0'..'9').toList())
val wordLetters = Gen.choose(
  20 to lower,
  20 to upper,
  10 to nums
)
val word = <Gen that chooses from wordLetters X times>
Gen.list(word).next().joinToString(separator = " ")
```

**Comment by LeoColman** [comment]
I think we should go for a Lorem Ipsum approach....

A sentence is composed of capital letters, periods, commas, flying commas.... Only characters help, but there is a lot of room for improvement

**Comment by LeoColman** [comment]
Or sentences from books or whatever like that

**Pull request closed without merging**
