### PR TITLE
Add similarity to haveValues and haveValue (#48)

### PR DESCRIPTION
**Pull request by AlexCue987**
add search for similar elements, such as:
```
            shouldThrow<AssertionError> {
               mapOf(
                  1 to sweetGreenApple,
                  2 to sweetRedApple,
                  3 to sourYellowLemon
               ).shouldContainValue(sweetGreenPear)
            }.message.shouldBe("""
            |Map should contain value Fruit(name=pear, color=green, taste=sweet)
            |Possible matches for missing value:
            |
            | expected: Fruit(name=apple, color=green, taste=sweet),
            |  but was: Fruit(name=pear, color=green, taste=sweet),
            |  The following fields did not match:
            |    "name" expected: <"apple">, but was: <"pear">
```

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Looks like a compile error after the merge. Duplicate declarations.

**Comment by AlexCue987** [comment]
yeah, I'll take care of that, hopefully tomorrow

**Comment by sksamuel** [comment]
> yeah, I'll take care of that, hopefully tomorrow

sweeet

**Comment by sksamuel** [comment]
@aSemy do you know why it is erroring on the JS repos?

**Comment by aSemy** [comment]
> @aSemy do you know why it is erroring on the JS repos?

The 'Build was configured to prefer settings repositories' warning message is unrelated.

I guess that the issue is because this PR is created from a fork, therefore it doesn't have access to the Kotest GitHub Action Secrets (which is correct), but for some reason they are being set as blank, and because blank strings != null, Gradle will enable signing with blank keys.

https://github.com/kotest/kotest/blob/e72b1bf0e8795909639dbf45c61f9831c587adb9/buildSrc/src/main/kotlin/kotest-publishing-conventions.gradle.kts#L22-L26

Hopefully https://github.com/kotest/kotest/pull/4233 fixes it...

**Comment by AlexCue987** [comment]
> > @aSemy do you know why it is erroring on the JS repos?
> 
> The 'Build was configured to prefer settings repositories' warning message is unrelated.
> 
> I guess that the issue is because this PR is created from a fork, therefore it doesn't have access to the Kotest GitHub Action Secrets (which is correct), but for some reason they are being set as blank, and because blank strings != null, Gradle will enable signing with blank keys.
> 
> https://github.com/kotest/kotest/blob/e72b1bf0e8795909639dbf45c61f9831c587adb9/buildSrc/src/main/kotlin/kotest-publishing-conventions.gradle.kts#L22-L26
> 
> Hopefully #4233 fixes it...

TY so much for investigating, @aSemy - I'll cut a new branch off of master in kotest, and move my changes to it. Hopefully that could fix all these issues.

**Comment by AlexCue987** [comment]
closed because too many conflicts, reopening as https://github.com/kotest/kotest/pull/4236

**Pull request closed without merging**
