### PR TITLE
platform independent shrinker

### PR DESCRIPTION
**Pull request by sielenk**
implementation for #2378

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Looks like a test failure.

**Comment by sielenk** [comment]
Hm. I was bold and placed the tests in `testCommon`. The failure happens for the JS code:

```
2021-09-17T14:40:56.4940802Z > Task :kotest-assertions:kotest-assertions-core:jsLegacyJar
2021-09-17T14:40:58.2368326Z e: /home/runner/work/kotest/kotest/kotest-property/src/commonTest/kotlin/com/sksamuel/kotest/property/shrinking/DoubleShrinkerTest.kt: (3, 18): Unresolved reference: core
2021-09-17T14:40:58.2369435Z 
2021-09-17T14:40:58.2370649Z > Task :kotest-property:compileTestKotlinJsLegacy FAILED
```

Something missing in `mainCommon`?
My Windows-Dev-System did not complain but seems to have its problems with the JS part.

I'll move the tests back to `jvmTest` for now.

**Comment by sksamuel** [comment]
Yeah jvmTest is best, as legacy jsTest is going away in 5.0

**Comment by sksamuel** [comment]
👍🏼

**Pull request merged**
