### PR TITLE
refactor: changed mutablity and visibility of EventaullyConfiguration

### LINKED ISSUE #4147: mutable Issue for `EventuallyConfigurationDefaults`
as mentioned here
#4018 

`EventuallyConfigurationDefaults` has some issues

1. since it's singleton object it's variables not thread safe and error prone if set to mutable
2. think it's visibility should change since default option should not change

because this issue is separate from #4018 
I will raise another pr after #4018 being merged

### PR DESCRIPTION
**Pull request by mirageoasis**
closes #4147 

as first mentioned in #4018 

I fixed visibility and mutability of `EventuallyConfigurationDefaults` since singleton object's concurrency issue may cause problem

### CODE REVIEW

**Comment by sksamuel** [comment]
can you run apiDump and commit the diff ?

**Comment by mirageoasis** [comment]
> can you run apiDump and commit the diff ?

ok~ I will run apiDump on evening!

**Comment by mirageoasis** [comment]
@sksamuel ran `apiDump` and merged main

**Comment by mirageoasis** [comment]
@sksamuel  can you rerun workflow for me?

**Comment by sksamuel** [comment]
> @sksamuel can you rerun workflow for me?

done

**Comment by mirageoasis** [comment]
think I have to create another pr to solve gpg issue

**Pull request closed without merging**
