### PR TITLE
Output response body on matcher failure log

### LINKED ISSUE #876: Improve ktor matcher
When you do this in ktor `response.shouldHaveStatus(200)` it would be useful if the error message contained the body as well, as that often contains a reason why it's not the expected code.

### PR DESCRIPTION
**Pull request by doyaaaaaken**
Fixes https://github.com/kotlintest/kotlintest/issues/876

### CODE REVIEW

**Comment by sksamuel** [comment]
What does this address ?

**Comment by doyaaaaaken** [comment]
@sksamuel 

In #876 , you said
> When you do this in ktor response.shouldHaveStatus(200) it would be useful if the error message contained the body as well

So, I change error message to contain response body `TestApplicationResponse.content` .

**Comment by sksamuel** [comment]
Oh. Is the content only available on the test version ?

**Comment by doyaaaaaken** [comment]
Ah! Sorry! 😮  I'll fix my code.

**Comment by doyaaaaaken** [comment]
Yes, `ApplicationResponse` does not have content.

**Comment by sksamuel** [comment]
Ok cool. Thanks, merging now.

**Pull request merged**
