### PR TITLE
Implement inline listeners and extensions in project config

### LINKED ISSUE #1764: Allow for inline registration of listeners and extensions in project config
**Please describe the feature you'd like to see including any solutions in mind if you have any**

### PR DESCRIPTION
**Pull request by LeoColman**
Closes #1764

### CODE REVIEW

**Comment by sksamuel** [comment]
The Pr is fine, but I've had this thought for a while that listeners/extensions should be registered in the same way (instead of two functions). I've not yet come up with a single name for the function that works, but something like `install`, `register`, `callback`, or something?

**Comment by LeoColman** [comment]
Perhaps. 
Do we want to do this now? And should we deprecate the other functions if we do

**Comment by sksamuel** [comment]
The reason I brought it up is because I don't think we should add 2 new methods if we plan to deprecate them very shortly after.

**Comment by LeoColman** [comment]
This is now conflicting. I'll close this until we decide on what we discussed above.

**Comment by sksamuel** [comment]
We can resurrect this. I'm happy to merge it.

**Comment by sksamuel** [comment]
If we can just fix the conflicts we're good.

**Comment by sksamuel** [comment]
We can close this or fix the conflicts.

**Pull request closed without merging**
