### PR TITLE
Implement String UUID matcher

### LINKED ISSUE #1119: String shouldbe UUID matcher

### PR DESCRIPTION
**Pull request by LeoColman**
Implements String UUID matching in accordance to RFC4122. The implementation details and discussion can be found at this StackOverflow thread: https://stackoverflow.com/questions/7905929/how-to-test-valid-uuid-guid

Closes #1119

### CODE REVIEW

**Comment by sksamuel** [comment]
Should we have a flag that allows the users to choose which type of uuid to match against ?
And if they don't specify it, then it matches all.
Then you could have 5 implementations and the "all" just iterates over them, rather than an uber regex ?

**Comment by LeoColman** [comment]
I think the difference between uuids is the way they are generated and one specific position, so the regex would stay.

Do you mean providing a `shouldBeV4uuid` or ` shouldBeUuid(V4)` ?

**Comment by sksamuel** [comment]
Yeah the latter.

**Comment by sksamuel** [comment]
Can we finish this and get it into master?

**Comment by LeoColman** [comment]
@sksamuel Please review again

**Review by sksamuel — APPROVED** [review]

**Pull request merged**
