### PR TITLE
Compiler plugin: fix IrLinkageError with K/Js on Kotlin 1.9

### LINKED ISSUE #3556: [Kotlin 1.9 Js] IrLinkageError if objects or abstract subclasses of AbstractProjectConfig exist in K/Js sources
**Kotest versions:** 5.6.2, Kotest master at commit 9d31ad7a46b5b706d587aad7d46d89344ea89a4e

The Kotest multiplatform plugin uses a Kotlin compiler plugin to instantiate subclasses of `AbstractProjectConfig` on K/Js and K/Native. Subclasses declared `abstract` or `sealed` cannot be instantiated. Neither can objects. However, the compiler plugin does not detect these cases and generates a constructor invocation nonetheless. Such behavior was tolerated on Js until Kotlin 1.8.21, but fails with Kotlin 1.9.0-Beta on Js:

Suppose we have the following in `commonTest`:
```kotlin
import io.kotest.core.config.AbstractProjectConfig

open class CommonProjectConfig(platform: String = "common") : AbstractProjectConfig() {
    init {
        kotestProjectConfig = platform
    }
}

var kotestProjectConfig: String = "?"
```

and this in `jsTest`:
```kotlin
object JsProjectConfig : CommonProjectConfig("js")
```

Kotlin 1.9.0-Beta on the Js platform produces:
```
> Task :compileTestDevelopmentExecutableKotlinJs
w: file:///home/oliver/.gradle/daemon/7.5/%3Ckotlin-multiplatform-arena_test%3E%20@%20/home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/src/commonTest/kotlin/CommonProjectConfig.ktConstructor 'JsProjectConfig.<init>' can not be called: 'JsProjectConfig' is object while class is expected
> Task :jsTestTestDevelopmentExecutableCompileSync
> Task :jsBrowserTest
  Uncaught IrLinkageError: Constructor 'JsProjectConfig.<init>' can not be called: 'JsProjectConfig' is object while class is expected
  at /home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/compileSync/js/test/testDevelopmentExecutable/kotlin/runtime/unlinked.kt:11:5 <- kotlin-multiplatform-arena-test.83974502.js:50216:5
```

If we now change `CommonProjectConfig` from `open` to `abstract`, Kotlin 1.9.0-Beta on the Js platform produces:
``` 
> Task :compileTestDevelopmentExecutableKotlinJs
w: file:///home/oliver/.gradle/daemon/7.5/%3Ckotlin-multiplatform-arena_test%3E%20@%20/home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/src/commonTest/kotlin/CommonProjectConfig.ktConstructor 'CommonProjectConfig.<init>' can not be called: Can not instantiate abstract class 'CommonProjectConfig'
w: file:///home/oliver/.gradle/daemon/7.5/%3Ckotlin-multiplatform-arena_test%3E%20@%20/home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/src/commonTest/kotlin/CommonProjectConfig.ktConstructor 'JsProjectConfig.<init>' can not be called: 'JsProjectConfig' is object while class is expected
> Task :jsTestTestDevelopmentExecutableCompileSync
> Task :jsBrowserTest
  Uncaught IrLinkageError: Constructor 'CommonProjectConfig.<init>' can not be called: Can not instantiate abstract class 'CommonProjectConfig'
  at /home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/compileSync/js/test/testDevelopmentExecutable/kotlin/runtime/unlinked.kt:11:5 <- kotlin-multiplatform-arena-test.83974502.js:50216:5
  IrLinkageError: Constructor 'CommonProjectConfig.<init>' can not be called: Can not instantiate abstract class 'CommonProjectConfig'
      at throwLinkageError (/home/oliver/Repositories/experimental/Issues/kotlin-multiplatform-arena/compileSync/js/test/testDevelopmentExecutable/kotlin/runtime/unlinked.kt:11:11 <- kotlin-multiplatform-arena-test.83974502.js:50216:11)
```

I'm currently preparing a PR to fix this.

### PR DESCRIPTION
**Pull request by OliverO2**
Fixes #3556 – IrLinkageError if objects or abstract subclasses of AbstractProjectConfig exist in K/Js sources

This commit makes the Kotest compiler plugin skip non-instantiable classes and objects, which derive from AbstractProjectConfig.

Note: To use objects deriving from AbstractProjectConfig on K/Js, they must be referenced at least once in code that executes, otherwise they will be discarded (with the IDE warning "object ... is never used").

### CODE REVIEW

**Comment by OliverO2** [comment]
Hmm, wondering why the compiler plugin is part of the API check. There should probably be an exclusion defined in an `apiValidation` block for the binary compatibility validator.

@sksamuel Should I act upon this? If so, as part of this PR or a separate one, which would have to be merged first?

**Comment by OliverO2** [comment]
Putting something like this in the top-level `build.gradle.kts` and then running `apiDump` would work:

```kotlin
apiValidation {
   ignoredPackages.addAll(
      listOf(
         "io.kotest.framework.multiplatform.embeddablecompiler",
         "io.kotest.framework.multiplatform.gradle",
         "io.kotest.framework.multiplatform.native"
      )
   )
}
```

**Comment by sksamuel** [comment]
Seems reasonable to me. Those packages are gonna change a lot.

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Nice work :)

**Comment by OliverO2** [comment]
Always a pleasure! :)

**Pull request merged**
