### PR TITLE
Remove mentions of kotest-assertions-collections from the docs

### LINKED ISSUE #4353: Review web docs / Remove obsolete kotest-assertions-collections
Hello, as I understand collection assertions are now part of core. Indeed, the artifact cannot be resolved at version 5.9.0.

[The web documentation](https://kotest.io/docs/assertions/matchers) should be reviewed and updated. I don't know if `kotest-assertions-collections` is the only obsolete package there. It misled me into thinking I needed the collections artifact.

### PR DESCRIPTION
**Pull request by okarmazin**
Closes #4353 

This module no longer exists, collection assertions are a part of core.

The table from `collections.md` was copied into `core.md` verbatim. `kotest-assertions-collections` was removed from the list of external modules, and `collections.md` was deleted.

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by okarmazin** [comment]
I can see that `validate-docs` fails, is there something else I should have done in this PR?

**Comment by LeoColman** [comment]
Apparently the side bar also had this page referenced
image

**Comment by LeoColman** [comment]
https://github.com/kotest/kotest/blob/a4ba30d0747b9235841d0fe932548c20f86993e3/documentation/sidebars.js#L75

I think right here

**Comment by okarmazin** [comment]
> https://github.com/kotest/kotest/blob/a4ba30d0747b9235841d0fe932548c20f86993e3/documentation/sidebars.js#L75
> 
> I think right here

Yeah! I searched for "collections.md", so this one slipped under the radar.

**Pull request merged**
