### PR TITLE
[NEXT RELEASE] #851 add docs to matchers.md

### PR DESCRIPTION
**Pull request by alladywek**

### CODE REVIEW

**Comment by LeoColman** [comment]
I'm wondering if we should add two versions of the "same" matcher to the documentation. Perhaps we can let the user discover that there's a default value set to 4? That way we can shorten the docs and avoid repetitions.

What do you think?

**Comment by alladywek** [comment]
Do you prefer method signature with precision?

**Comment by LeoColman** [comment]
Yes, I think it's better to keep only the method signature with precision.
```
 | `collection.shouldHaveMean(mean, precision)` | Asserts that collection has specific mean with specific precision | 
```

But we can discuss this further if you don't agree

**Comment by alladywek** [comment]
I don't have objections regarding to left one signature, I think that maybe in this case we need change description, e.g.:

```
 | `collection.shouldHaveMean(mean, precision)` | Asserts that collection has mean with specific or default (4 digits after decimal point) precision |
```

What do you think?

**Comment by LeoColman** [comment]
That's better :)

**Pull request merged**
