### PR TITLE
Added tests for Spring Boot integration

### LINKED ISSUE #782: Improve and validate kotlintest works with spring boot
Including things like @ActiveProfile

### PR DESCRIPTION
**Pull request by LeoColman**
Fixes #782

### CODE REVIEW

**Comment by LeoColman** [comment]
@sksamuel 
I added these tests to our spring extension. This is exactly how I test Spring Boot (I use Spring Boot all the time at my company), and I believe we're currently supporting it correctly.

**Comment by sksamuel** [comment]
Funny, I was thinking of doing something like this myself today!

**Review by sksamuel — APPROVED** [review]

**Comment by LeoColman** [comment]
Beat you to it! xD

**Comment by sksamuel** [comment]
I'd like us to add support for Koin.

**Comment by LeoColman** [comment]
#515

**Comment by sksamuel** [comment]
Koin 2.0 has come out, so if would be good if we do this.
I will make a roadmap for 3.4

**Pull request merged**
