### PR TITLE
Bump Arrow version 0.10.3

### PR DESCRIPTION
**Pull request by lenguyenthanh**
Bump Arrow version [0.10.2](https://github.com/arrow-kt/arrow/releases/tag/0.10.2)

### CODE REVIEW

**Comment by lenguyenthanh** [comment]
I think we can wait for 0.10.3: https://github.com/arrow-kt/arrow/pull/1792

**Comment by lenguyenthanh** [comment]
Used Arrow 0.10.3

**Comment by sksamuel** [comment]
seems to fail in travis.

**Comment by lenguyenthanh** [comment]
`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.` The failed message seems weigh to me. 

It was success in travis with 0.10.2 before. And A clean build works in my machine.

Can you try to re-run travis?

**Comment by LeoColman** [comment]
Triggered a rerun

**Comment by LeoColman** [comment]
Thanks!
Meged

**Pull request merged**
