### PR TITLE
Trying to fix #485

### LINKED ISSUE #485: Runtime JAR files in the classpath have the version 1.2
Kotlintest is bringing into the classpath older dependencies which can cause problems

```
w: Runtime JAR files in the classpath have the version 1.2, which is older than the API version 1.3. Consider using the runtime of version 1.3, or pass '-api-version 1.2' explicitly to restrict the available APIs to the runtime of version 1.2. You can also pass '-language-version 1.2' instead, which will restrict not only the APIs to the specified version, but also the language features
w: C:\Users\gbarbieri\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.2.50\9fab8887f91c8e17cce1a7522f45dc25976e57b9\kotlin-reflect-1.2.50.jar: Runtime JAR file has version 1.2 which is older than required for API version 1.3
w: C:\Users\gbarbieri\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.2.50\6b19a2fcc29d34878b3aab33fd5fcf70458a73df\kotlin-stdlib-common-1.2.50.jar: Runtime JAR file has version 1.2 which is older than required for API version 1.3
w: C:\Users\gbarbieri\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.2.31\95d6a67e8787280a82a2059e54e4db7ac6cfe74\kotlin-stdlib-jdk7-1.2.31.jar: Runtime JAR file has version 1.2 which is older than required for API version 1.3
w: C:\Users\gbarbieri\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.2.50\66d47b004c5b8a1d2d1df9e463187390ed741316\kotlin-stdlib-1.2.50.jar: Runtime JAR file has version 1.2 which is older than required for API version 1.3


\--- io.kotlintest:kotlintest-runner-junit5:3.1.10
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.50 -> 1.3.10 (*)
     +--- io.kotlintest:kotlintest-core:3.1.10 (*)
     +--- io.kotlintest:kotlintest-assertions:3.1.10 (*)
     +--- io.kotlintest:kotlintest-runner-jvm:3.1.10
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.50 -> 1.3.10 (*)
     |    +--- io.kotlintest:kotlintest-core:3.1.10 (*)
     |    +--- org.reflections:reflections:0.9.11
     |    |    +--- com.google.guava:guava:20.0
     |    |    \--- org.javassist:javassist:3.21.0-GA
     |    +--- org.slf4j:slf4j-api:1.7.25
     |    \--- io.arrow-kt:arrow-core:0.7.1
     |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.31
     |         |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.2.31 -> 1.3.10 (*)
     |         \--- io.arrow-kt:arrow-annotations:0.7.1
     |              +--- org.jetbrains.kotlin:kotlin-stdlib:1.2.31 -> 1.3.10 (*)
     |              \--- io.kindedj:kindedj:1.1.0
     +--- org.junit.platform:junit-platform-engine:1.2.0
     |    +--- org.apiguardian:apiguardian-api:1.0.0
     |    +--- org.junit.platform:junit-platform-commons:1.2.0
     |    |    \--- org.apiguardian:apiguardian-api:1.0.0
     |    \--- org.opentest4j:opentest4j:1.1.0
     +--- org.junit.platform:junit-platform-suite-api:1.2.0
     |    +--- org.apiguardian:apiguardian-api:1.0.0
     |    \--- org.junit.platform:junit-platform-commons:1.2.0 (*)
     \--- org.junit.platform:junit-platform-launcher:1.2.0
          +--- org.apiguardian:apiguardian-api:1.0.0
          \--- org.junit.platform:junit-platform-engine:1.2.0 (*)
```
I was suggested to explicit add a dependency to `kotlin-reflect` `1.3.10`, but this not always seems to work

### PR DESCRIPTION
**Pull request by elect86**

### CODE REVIEW

**Comment by sksamuel** [comment]
:+1:

**Comment by elect86** [comment]
Hey Stephen,

can we get a release for that?

**Comment by elect86** [comment]
Nice, may I ask an eta?

**Comment by sksamuel** [comment]
Hopefully next few days. You can track it here.
https://github.com/kotlintest/kotlintest/issues/489

**Comment by elect86** [comment]
Hey Stephen,

it looks like 3.1.11 didnt solve it.. 

Are these modifications in? 

What can we do?

**Comment by sksamuel** [comment]
Can you try 3.2 RC2 ?

**Comment by elect86** [comment]
Tried 3.2.0, it seems fine.

What was the working fix?

**Comment by sksamuel** [comment]
Something else was bringing it in, can't remember what now.

**Pull request merged**
