### PR TITLE
Add support of Equality to all contain* matchers

### PR DESCRIPTION
**Pull request by pientaa**
Implements #3480 

Add verifier parameter to all the following functions: containAll, containExactly, containExactlyInAnyOrder, containOnly

### CODE REVIEW

**Comment by sksamuel** [comment]
I wonder if we should just use the Eq typeclass that we already have. Thoughts?

**Comment by pientaa** [comment]
@sksamuel we already use `Equality` in `contain` and it differs a lot from `Eq`:
image
image

So I don't think that @neckbosov meant it in #3480

Maybe `Eq` and `Equality` should be merged in the future? But this will be a bigger change, not in scope of my changes.

**Comment by sksamuel** [comment]
Yeah I'm worried if we add Equality everywhere it will be hard to replace it with Eq later.

Let me think on this one.

**Comment by pientaa** [comment]
@sksamuel personally, I'd create another issue for merging `Eq` and `Equality`. I can pick this up if you don't mind

**Comment by sksamuel** [comment]
Ok we can merge this in as it is, but first can you make overloads rather than adding default values.
This will keep the API dump the same for existing methods.

**Comment by pientaa** [comment]
@sksamuel done

**Review by sksamuel — APPROVED** [review]

**Pull request merged**
