### PR TITLE
Reduce the size of stack traces (2)

### PR DESCRIPTION
**Pull request by angusholder**
Finishes what I started in #4308, doing the same for SpecInterceptor and SpecRefInterceptor too.

I had to change `ClassVisibilitySpecRefInterceptor` to internal to get it to compile. I might be missing something but it seems like a mistake that that class was made public in the first place? It only implements the internal `SpecRefInterceptor` interface, and doesn't seem to have any utility otherwise. It was introduced in this commit 22nd July https://github.com/kotest/kotest/commit/3b196b1b598aec01de26ca37a52e505391e6ece5

Alternatively I could change `NextSpecRefInterceptor` to `@KotestInternal` and leave that class public.

### CODE REVIEW

**Comment by AlexCue987** [comment]
tests failing as follows: "java.lang.ClassCastException: kotlin.Result cannot be cast to java.util.Map"

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
i tried to fix this but couldn't. No idea why the compiler is complaining, it looks fine to me.
Might need to make a new PR which does this bit by bit. If the original author is not around, I can pick it up.

**Comment by sksamuel** [comment]
Got this working via #4400  and #4403 so closing this.

**Comment by angusholder** [comment]
Thanks @sksamuel! I hadn't had the chance to take another look yet

**Pull request closed without merging**
