### PR TITLE
Fix contain exactly verifier

### PR DESCRIPTION
**Pull request by AlexCue987**
fix the following issue: https://github.com/kotest/kotest/issues/3970

### CODE REVIEW

**Comment by sksamuel** [comment]
Is this ready for review @AlexCue987 ?

**Comment by AlexCue987** [comment]
> Is this ready for review @AlexCue987 ?

yes

**Comment by AlexCue987** [comment]
> Is this ready for review @AlexCue987 ?

it's ready to go @sksamuel

**Comment by sksamuel** [comment]
Failing tests

**Comment by sksamuel** [comment]
Error here:
e: file:///Users/runner/work/kotest/kotest/kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/com/sksamuel/kotest/matchers/collections/ShouldContainExactlyTest.kt:6:25 Conflicting import, imported name 'Equality' is ambiguous

**Comment by sksamuel** [comment]
Fixing tests

**Review by sksamuel — APPROVED** [review]

**Pull request merged**
