### PR TITLE
[NEXT RELEASE] Adds documentation for regex matchers

### PR DESCRIPTION
**Pull request by ashishkujoy**
Regex Matchers were implement in #1074 , this PR adds documentation for the same.

### CODE REVIEW

**Comment by ashishkujoy** [comment]
Hi @sksamuel, any idea by when we will merge this pull request

**Comment by LeoColman** [comment]
@ashishkujoy 
The matchers aren't released yet, so we can only merge documentation when they're released as not to confuse current/future users

**Comment by LeoColman** [comment]
@ashishkujoy 
I think this PR contains some commits that shouldn't be here.
Would you mind to rebase this without those commits?

**Comment by ashishkujoy** [comment]
> @ashishkujoy
> I think this PR contains some commits that shouldn't be here.
> Would you mind to rebase this without those commits?

Done

**Pull request merged**
