### PR TITLE
Add experimental robolectric support

### LINKED ISSUE #926: Add support to Robolectric

### PR DESCRIPTION
**Pull request by LeoColman**
Part of #189
Closes #926

### CODE REVIEW

**Comment by LeoColman** [comment]
Currently I didn't find any good way to test this other than trying to run tests in my own projects, so IDK how to validate this idea.

Help wanted on this experimental approach

**Comment by LeoColman** [comment]
@sksamuel 
I don't think there's a lot to discuss on this. I think you're very up-to-date on what this extension is about, so I'll merge it to allow a snapshot build for people to test it.

**Comment by sksamuel** [comment]
Cool

**Comment by nikhilkumar80** [comment]
@Kerooker , could you please give an example of how to use this extension?

**Comment by LeoColman** [comment]
Sure!

- Create a ProjectConfig (guide [here](https://github.com/kotlintest/kotlintest/blob/master/doc/reference.md#project-config))
- override the `extensions` method to include `RobolectricExtension`
- Use the annotation `RobolectricTest` to any class that you need Robolectric support

**Pull request merged**
