### PR TITLE
Implement should contain any matcher

### LINKED ISSUE #946: New matcher: shouldContainAny and shouldNotContainAny
A handy matcher to say that a collection should contain any of the provided elements - at least one is sufficient to pass.

### PR DESCRIPTION
**Pull request by LeoColman**
Closes #946

### CODE REVIEW

**Comment by sksamuel** [comment]
Maybe shouldContainAnyOf ?

**Comment by LeoColman** [comment]
You think it's better?

**Comment by sksamuel** [comment]
Yes because shouldContain is one element and this is any from the list.
It's clearer to say anyOf

**Comment by sksamuel** [comment]
If you rename this then you can merge.

**Comment by LeoColman** [comment]
Yep. Merging when green

**Pull request merged**
