### PR TITLE
Collection assertions

### LINKED ISSUE #2145: Why does shouldHaveSingleElement and other Collection "shoulds" have predicate instead of block for assertions?
What I do not really get is: when does your library want predicates (T)->Boolean and when does it require a function block that itself can do multiple assertions using matchers and should constructs?

I.e.:
```
list.shouldHaveSingleElement {
   it.name == "Bob"
}
```

vs. (not the case)
```
list.shouldHaveSingleElement {
  it.name shouldBe "Bob"
}
```

I've stumbled across both ways, but the simple predicate one is used for collections - and I do not like it at all, because the error messages don't reveal any reason for failing the match whereas the latter one could state that something was expected to be "Bob" but is "Alice" for example.

Is there a reason behind this that I cannot see?

### PR DESCRIPTION
**Pull request by Kantis**
Highlights:
* Deprecates `shouldExist` in favor of `forAny` 
* Adds `forSingle` inspector, that asserts that a collection has a single element, which matches the assertion
* Adds lambda-based alternatives to predicate-based `existInOrder` matcher
  *  `matchEach` 1:1 match element:assertion
  * `matchInOrder` assert in order, with no gaps
  * `matchInOrderSubset` assert in order, gaps allowed

### CODE REVIEW

**Comment by Kantis** [comment]
Any feedback on the naming of `existInAssertedOrder()`? 

I would ideally have liked to use `existInOrder(assertions: List<(T) -> Unit>)` for this one as well, but it seemed to clash with the existing `existInOrder(ps: List<(T) -> Boolean>)`

**Comment by sksamuel** [comment]
I don't like the name `existInAssertedOrder`. 
Perhaps `shouldAssertInOrder` but we need one that works with gaps and one that doesn't.

`shouldAssertSubset` <- gaps ?
`shouldAssert` <- no gaps ?

**Comment by Kantis** [comment]
`shouldAssert` means the matcher would be named `assert`? I think that might be confusing?

Maybe `shouldFullyMatch`, `shouldPartiallyMatch`? 🤔

I agree it would be nice to offer both a complete match opportunity, and a subset match.. Perhaps it would also be nice to be able to specify if they shouold exist in order or not..

**Comment by sksamuel** [comment]
shouldPassEach

shouldApplyInOrder

shouldAssertEach

**Comment by Kantis** [comment]
`shouldMatchInOrder` - Test vararg of assertions against collection, does not require exhaustive test
`shouldMatchInOrderWithoutGaps` - same as above, disallowing gaps
`shouldMatchAll` - same as above, but must be exhaustive for the list. E..g assertion 1 must pass element 1, and one assertion must exist for each element

Matchers would then be `matchAll` and `matchInOrder`, latter taking a parameter to decide whether gaps are allowed. 

Do you prefer another verb?

**Comment by sksamuel** [comment]
I think those names should good, and maybe shouldMatchInOrderWithoutGaps could be shouldMatchInOrderSubset

**Comment by sksamuel** [comment]
@Kantis can you rebase whenever you're able :)

**Comment by sksamuel** [comment]
@Kantis do you have time to finish this up for 5.1 release this week?
If not I can move to 5.2

**Comment by Kantis** [comment]
> @Kantis do you have time to finish this up for 5.1 release this week? If not I can move to 5.2

I'll try ✌🏼 Sorry for not responding for a while, I mentally checked out over the holidays

**Comment by sksamuel** [comment]
So did I. Was wonderful :)

**Comment by Kantis** [comment]
@sksamuel this one's ready ✌🏼

**Comment by sksamuel** [comment]
It's been a while :)
Can you remind me what the matchEach is solving again.

**Pull request merged**
