### PR TITLE
Feature/2656 inspectors for maps #2656

### PR DESCRIPTION
**Pull request by pientaa**
Implements kotest/kotest#2656

I've implemented inspectors for maps. I took a look at the way you wrote it for collections. 

I noticed that there are missing tests in `InspectorsTest` (e.g. for `forAtLeastOne` and `forAtMostOne`), so I'm going to write them soon, but this test class is getting too big (~1k lines of code :scream:) and that's why I'd like to separate inspectors' tests into more files. I'm thinking of creating separate test class for each of: `Collection` and `Map`. What do you think?

### CODE REVIEW

**Comment by sksamuel** [comment]
You could split each inspector type into it's own test file.

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Let me know when you're happy with the PR and I'll give it a final look over and merge.

**Comment by pientaa** [comment]
> Let me know when you're happy with the PR and I'll give it a final look over and merge.

I think, I'm happy with the PR

**Comment by pientaa** [comment]
@sksamuel IMHO PR is ready to be merged

**Comment by sksamuel** [comment]
It looks great, but will wait until 5.0.1 is out (later tonight) as I want this in 5.1.0 only (its a new feature, not a bug fix).

**Pull request merged**
