### PR TITLE
`Arb.list` implementation supporting `Arb<IntRange>` and `Arb.intRange`

### PR DESCRIPTION
**Pull request by lexa-diky**
- added Arb.list implementation supporting Arb<IntRange>
- added Arb.intRange

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
awesome thanks

**Comment by sksamuel** [comment]
We need to add the api dump gradle task output to this PR

**Comment by lexa-diky** [comment]
Oh, sorry, forgot to put draft on it. Thank you for reminding about api dump. Will add some tests and we are good to go.

**Review by Kantis — APPROVED** [review]
Nice, thanks :)

**Pull request merged**
