### PR TITLE
Add matchers for ResultSet.

### PR DESCRIPTION
**Pull request by dragneelfps**
Contains `java.sql.ResultSet` assertion matchers

Inspired from https://github.com/kotest/kotest/issues/961

### CODE REVIEW

**Review by sksamuel — APPROVED** [review]
Looks great. We could also add one that checks for the presence of a row based on a lamda.

**Comment by dragneelfps** [comment]
> Looks great. We could also add one that checks for the presence of a row based on a lamda.

That will be interesting. Will add it

**Comment by dragneelfps** [comment]
@sksamuel I have added the row assertion. Also, I changed the column value assertion to use generics which enables us to have different specific types in the lambda block of the assertion.

**Comment by sksamuel** [comment]
Excellent.

**Pull request merged**
