### PR TITLE
Move more commons out to the projects that need it

### PR DESCRIPTION
**Pull request by sksamuel**
As part of 6.0 all deprecated methods are being removed.

### CODE REVIEW

**Review by OliverO2 — APPROVED** [review]
A bit hard to review, but at least I could not find any obvious problems. Just seems that the lexicographic order of import statements is now broken.

**Comment by sksamuel** [comment]
> A bit hard to review, but at least I could not find any obvious problems. Just seems that the lexicographic order of import statements is now broken.

I've just moved things about, no code changes.

Is there a setting in intellij for the order ?

**Comment by OliverO2** [comment]
> Is there a setting in intellij for the order ?

I'm not sure, I'm using the Ktlint plugin with auto-formatting on save for my own stuff. That one does ordering. I suppose IntelliJ by default does that, too, as it has also settings on whether to accept star imports and such.

**Comment by sksamuel** [comment]
> > Is there a setting in intellij for the order ?
> 
> I'm not sure, I'm using the Ktlint plugin with auto-formatting on save for my own stuff. That one does ordering. I suppose IntelliJ by default does that, too, as it has also settings on whether to accept star imports and such.

I have star imports disabled.

**Comment by OliverO2** [comment]
Yeah, me too. Just mentioned it to support my suspicion that IJ can be pretty opinionated wrt. imports.

**Pull request merged**
