### PR TITLE
Add more primative gens

### LINKED ISSUE #772: Generators for Byte, Short, and experimental unsigned types
It seems straightforward to add them. I can submit a pull request if desired.

### PR DESCRIPTION
**Pull request by magneticflux-**
Closes #772

### CODE REVIEW

**Comment by sksamuel** [comment]
lgtm merge when you're happy @Kerooker

**Comment by sksamuel** [comment]
Thanks for the pr @magneticflux-

**Comment by Kerooker** [comment]
Could we add some tests for these new generators?

**Review by LeoColman — CHANGES_REQUESTED** [review]
We should add some tests for the new generators, to ensure that we won't break them in the future. If you can't create the tests right now or whatever reason, please let us now, and we can do it for you :)

**Comment by magneticflux-** [comment]
I added to some existing tests, but I didn't see any other tests for the original Int and Long gens to parallel for Short and Byte. If you want more tests, just link where I should put them and I'll add them!

**Comment by LeoColman** [comment]
I think we're ok for now.
I'll add some tests for all of these later.

Thanks for the PR, @magneticflux- !

**Pull request merged**
