### PR TITLE
Disable autoscan of config classes; Check for well known config FQN by default

### LINKED ISSUE #3746: Performance regression with Kotest 5.7.x classpath scanning
Since Kotest 5.7, classpath scanning for Extensions and Config has become very slow, adding multiple minutes to a test run.

This does NOT seem related to #3670 

## Tested Kotest versions

5.6.2 vs. 5.7.2

## Note 

Since it is not a public project where I noticed the issue first, I can't give access to the sources. 
I also did not (yet) check on any other project yet, if that issue is reproducible there as well. I will add this if I find a public reproducer.

## Description

I have a small/medium sized Spring Boot Application, using Maven as a build tool. The project does not have any Kotest specific configuration (no `AbstractProjectConfig`, no `kotest.properties`). 

Prior to Kotest 5.7, this setup went well, and also auto-registered the `SpringAutowireConstructorExtension`, which we use heavily for injecting beans in Spring integration tests. 

Now, with Kotest 5.7.2, Maven makes a large pause during test startup (see below).

Executing `./mvnw test` makes a pause of multiple minutes between the `TESTS` banner and actually executing tests in Kotest 5.7.2. When using Kotest 5.6.2 (everything else the same), the pause is only a few seconds. See example logs below.

It seems to be depending on the size of the project (or amount of dependencies, or tests...?), but the pause makes the major contribution to the total runtime of `./mvnw test`. In one project, the pause is 8 minutes of about 11 total execution time, in the other it is about 3:30 of 4:30 minutes.

## Workaround 

I found, that, if I disable the classpath scanning by adding a `kotest.properties` like below, and add a ProjectConfig to register the `SpringAutowireConstructorExtension` manually, the pause vanishes. If I set one of the flags to false, the pause is approximately half as long.

So it seems the classpath scanning feature (which itself predates 5.7) has received a major performance regression in 5.7.

```
kotest.framework.classpath.scanning.config.disable=true
kotest.framework.classpath.scanning.autoscan.disable=true
kotest.framework.config.fqn=my.path.to.KotestConfiguration
```
 
## Details

Timed output of `./mvnw test | ts` using 5.7.2

```
Oct 26 13:44:36 [INFO] --- surefire:3.2.1:test (default-test) @ ... ---
Oct 26 13:44:37 [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
Oct 26 13:44:37 [INFO] 
Oct 26 13:44:37 [INFO] -------------------------------------------------------
Oct 26 13:44:37 [INFO]  T E S T S
Oct 26 13:44:37 [INFO] -------------------------------------------------------
Oct 26 13:48:04 [INFO] Running ... (first test class name)
```

Timed output of `./mvnw test | ts` using 5.6.2

```
Oct 26 13:56:31 [INFO] --- surefire:3.2.1:test (default-test) @ ... ---
Oct 26 13:56:31 [INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
Oct 26 13:56:31 [INFO] 
Oct 26 13:56:31 [INFO] -------------------------------------------------------
Oct 26 13:56:31 [INFO]  T E S T S
Oct 26 13:56:31 [INFO] -------------------------------------------------------
Oct 26 13:56:37 [INFO] Running ... (first test class name)
```

### LINKED ISSUE #3895: Execution fails with "Retried waiting for GCLocker too often allocating"
When testing my module, it fails with errors like:

```
[4.776s][warning][gc,alloc] ClassGraph-worker-15: Retried waiting for GCLocker too often allocating 1026 words
```

This occurs for a module which does not define any Kottest tests. Simply adding kotest as a test dependency causes this error, and removing it as a dependency prevents the error.

This does not occur on all of my modules. I suspect it is only happen on those with a larger amount of items on the classpath.

Kotest version: 5.8.0
Gradle version: 8.6
Gradle-JVM version: temurin-20.0.2

### LINKED ISSUE #4112: CI: test_linux(jvmTest) fails intermittently with OutOfMemoryError: Java heap space
Kotest 5.9.1/master at 846f0a66f795eb0ef419cc2fbebbe1c0c2c51647

[In the logs](https://github.com/kotest/kotest/actions/runs/9536396785/job/26283311789), we occasionally see

```
Warning: [107.675s][warning][gc,alloc] ClassGraph-worker-306: Retried waiting for GCLocker too often allocating 1026 words
```

followed by
```
> Task :kotest-runner:kotest-runner-junit5:jvmTest

com.sksamuel.kotest.runner.junit5.StringSpecEngineKitTest[jvm]
Test exception in beforeSpec override[jvm] FAILED
org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'kotest' failed to discover tests
Caused by: io.kotest.engine.config.ConfigurationException: io.github.classgraph.ClassGraphException: Uncaught exception during scan
Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
Caused by: java.lang.OutOfMemoryError: Java heap space
```

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #3895 caused by poor performance

Fixes #4112 too possibly.

Fixes #3746

### CODE REVIEW

**Comment by sksamuel** [comment]
This PR disables the config lookup by classgraph scanning.
Instead we look for io.kotest.provided.ProjectConfig and instantiate that. Users can override that FQN by setting their own (like they could before) via a system property.

**Review by OliverO2 — APPROVED** [review]

**Comment by 1Mark** [comment]
When will this be tagged & released please?

**Comment by sksamuel** [comment]
You can use the snapshot that's auto built on every merge.

**Comment by LeoColman** [comment]
I love how we went back and forth on this feature over the releases

**Comment by OliverO2** [comment]
I'd love to see it coming back via a compiler plugin with a zero performance penalty.

**Pull request merged**
