### PR TITLE
Bump gradle wrapper version 5.6.2

### PR DESCRIPTION
**Pull request by lenguyenthanh**

### CODE REVIEW

**Comment by LeoColman** [comment]
Did you configure those comments and configs yourself?
Or they're included from the new gradle version?

**Comment by lenguyenthanh** [comment]
I used ` ./gradlew wrapper --gradle-version 5.6.2 --distribution-type all` command. So all files were generated.

**Comment by LeoColman** [comment]
Ok, great!
Thanks for this contribution :)

**Comment by lenguyenthanh** [comment]
You're welcome. Thanks for a great library.

**Pull request merged**
