### PR TITLE
Replace nativeMain source set with individual targets

### LINKED ISSUE #1468: Can not build kotest
**Which version of Kotest are you using**
master
When I run on my Ubuntu machine build task I get output
```
Could not determine the dependencies of task ':kotest-assertions:kotest-assertions-core:compileKotlinLinuxX64'.
> Could not resolve all task dependencies for configuration ':kotest-assertions:kotest-assertions-core:linuxX64CompileKlibraries'.
   > Could not resolve project :kotest-assertions:kotest-assertions-shared.
     Required by:
         project :kotest-assertions:kotest-assertions-core
      > Cannot choose between the following variants of project :kotest-assertions:kotest-assertions-shared:
          - apiElements
          - linuxX64ApiElements
          - linuxX64Compile
          - linuxX64CompileOnly
          - linuxX64Default
          - linuxX64RuntimeOnly
          - linuxX64TestCompile
          - nativeApiElements
          - nativeCompile
          - nativeCompileOnly
          - nativeDefault
          - nativeRuntimeOnly
          - nativeTestCompile
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'apiElements' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.dependency.bundling 'external' but wasn't required.
                  - Found org.gradle.jvm.version '8' but wasn't required.
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-api'.
          - Variant 'linuxX64ApiElements' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attribute:
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64Compile' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64CompileOnly' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64Default' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64RuntimeOnly' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
          - Variant 'linuxX64TestCompile' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeApiElements' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attribute:
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeCompile' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeCompileOnly' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeDefault' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeRuntimeOnly' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
          - Variant 'nativeTestCompile' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-assertions:kotest-assertions-shared' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'runtimeElements' capability io.kotest:kotest-assertions-shared:4.0.2:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.dependency.bundling 'external' but wasn't required.
                  - Found org.gradle.jvm.version '8' but wasn't required.
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-runtime'.
   > Could not resolve project :kotest-mpp.
     Required by:
         project :kotest-assertions:kotest-assertions-core
      > Cannot choose between the following variants of project :kotest-mpp:
          - apiElements
          - linuxX64ApiElements
          - linuxX64Compile
          - linuxX64CompileOnly
          - linuxX64Default
          - linuxX64RuntimeOnly
          - linuxX64TestCompile
          - nativeApiElements
          - nativeCompile
          - nativeCompileOnly
          - nativeDefault
          - nativeRuntimeOnly
          - nativeTestCompile
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'apiElements' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.dependency.bundling 'external' but wasn't required.
                  - Found org.gradle.jvm.version '8' but wasn't required.
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-api'.
          - Variant 'linuxX64ApiElements' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attribute:
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64Compile' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64CompileOnly' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64Default' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'linuxX64RuntimeOnly' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
          - Variant 'linuxX64TestCompile' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeApiElements' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attribute:
                  - Found org.jetbrains.kotlin.localToProject 'public' but wasn't required.
              - Compatible attributes:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'kotlin-api'.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeCompile' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeCompileOnly' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeDefault' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'nativeRuntimeOnly' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
          - Variant 'nativeTestCompile' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Required org.gradle.usage 'kotlin-api' but no value provided.
                  - Found org.jetbrains.kotlin.localToProject 'local to :kotest-mpp' but wasn't required.
              - Compatible attributes:
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' and found compatible value 'linux_x64'.
                  - Required org.jetbrains.kotlin.platform.type 'native' and found compatible value 'native'.
          - Variant 'runtimeElements' capability io.kotest:kotest-mpp:4.0.2:
              - Unmatched attributes:
                  - Found org.gradle.category 'library' but wasn't required.
                  - Found org.gradle.dependency.bundling 'external' but wasn't required.
                  - Found org.gradle.jvm.version '8' but wasn't required.
                  - Found org.gradle.libraryelements 'jar' but wasn't required.
                  - Required org.jetbrains.kotlin.native.target 'linux_x64' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'native' but no value provided.
              - Compatible attribute:
                  - Required org.gradle.usage 'kotlin-api' and found compatible value 'java-runtime'.

```

### PR DESCRIPTION
**Pull request by ajalt**
This is an alternate approach to the one taken in #1472

This copies all native code from the previous common `nativeMain` source set into source sets for each individual target. This results in some code duplication, but otherwise should work with both IntelliJ and gradle.

Fixes #1468

### CODE REVIEW

**Comment by sksamuel** [comment]
Almost the same as #1475 except you always define every target. Will this cause problems when the platform isn't available? The approach I took in #1475 is to pick the one native platform that is available. I don't know if that's better or worse or no practical difference.

**Comment by ajalt** [comment]
You always want to enable all the targets. With this setup, IntelliJ is able to autocomplete all targets code, even if you can't compile that target on the current OS. If you only enable the current OS target, the other targets' code would be full of errors in IntelliJ.

**Comment by sksamuel** [comment]
Are you sure, because if they're not even defined, intellij doesn't see them as sourcesets.

**Comment by ajalt** [comment]
Right. If IntelliJ doesn't see them as source sets, it won't be able to highlight and complete them correctly. If you're on the fence, I'd suggest checking out out each branch and seeing what the editing experience is like for a native target that isn't your current OS.

**Comment by sksamuel** [comment]
I don't understand what you mean by highlight from them correctly? Like I'm developing on linux, I don't even want the macos sourceset to be a sourceset. It can just be a random directly. And viceversa when running on a macos?

Sorry to keep asking questions, you just know more about this stuff than me.

**Comment by ajalt** [comment]
Please ask as many questions as you want.

> I'm developing on linux, I don't even want the macos sourceset to be a sourceset

Why not? It's totally reasonable to write code for a different platform, then push it up to CI to test. I don't have a mac, but I still write code for the macos target. I develop on windows, and I could spin up a ubuntu VM to work on the linux target, but it's much easier to write the code from the same OS I normally use.

**Comment by sksamuel** [comment]
That makes sense. Kind of how I added the same code for 3 targets in my pr.

**Pull request merged**
