### PR TITLE
JSON Shema: DSL improvements and make properties required by default

### PR DESCRIPTION
**Pull request by Kantis**
Object properties are now required by default in the DSL. Users can specify `optional = true` to enable nullability instead.

### CODE REVIEW

**Comment by Kantis** [comment]
I'd like to get this in with the next release. Just want to update docs a bit more before merging

**Comment by sksamuel** [comment]
Probably do 5.4 in june.

**Comment by sksamuel** [comment]
All lgtm

**Comment by sksamuel** [comment]
@Kantis thinking we could release 5.4 later today or tomorrow. Did you want to get this in ?

**Comment by Kantis** [comment]
AFK for a bit. Can try to fix the build tomorrow morning and merge if successful. It's not a huge problem if it misses the release though.. :)

**Review by sksamuel — APPROVED** [review]

**Pull request merged**
