### PR TITLE
Move constant now to new module; bump junit to 1.8.2

### LINKED ISSUE #3433: JUnit Platform Version Clash
**Version**: 5.5.5 (currently latest)

**To reproduce**: Gradle build with JUnit JVM runner `io.kotest:kotest-runner-junit5-jvm` during testing throws (does not break the build)
```
java.lang.NoSuchMethodError: 'org.junit.platform.engine.ConfigurationParameters org.junit.platform.launcher.TestPlan.getConfigurationParameters()
```

**Reason**: Currently, used JUnit platform version (e.g. in JVM runner artifact) is `1.7.2` but it clashes with version that is transitively provided from `org.junit.jupiter:junit-jupiter` (version `5.8.2`) that uses `1.8.2`. So in the end, there are various platform JARs in the classpath (e.g. engine in `1.8.2` while launcher `1.7.2` etc...)

**How To Fix**: Upgrade JUnit platform version in [libs.versions.toml](https://github.com/kotest/kotest/blob/master/gradle/libs.versions.toml#L10) to `1.8.2` (or even newer `1.9.2`)

**Wokraround**: Specify (override) version of JUnit platform libraries in the project that uses kotest with JUnit runner, e.g.:
```
testImplementation("org.junit.platform:junit-platform-commons:1.8.2")
testImplementation("org.junit.platform:junit-platform-launcher:1.8.2")
testImplementation("org.junit.platform:junit-platform-engine:1.8.2")
testImplementation("org.junit.platform:junit-platform-suite-api:1.8.2")
```

Side note, also consider excluding `junit:junit` (legacy JUnit4) from `kotest-extensions-jvm` that have it transitively via `io.mockk:mockk-jvm:1.13.1`

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #3433 #3391

Bumps junit to 1.8.2
Moves the constant now extensions to a new module that avoids bringing mockk into the regular extensions.

### CODE REVIEW

**Review by i-walker — APPROVED** [review]

**Comment by obecker** [comment]
Apparently `MutableClock` has been silently removed. I don't see any connection to the linked issues. Could you please share what the proper replacement is? Thank you.

**Comment by sksamuel** [comment]
The test clock extensions module.

**Comment by obecker** [comment]
Ah, ok. It's the `TestClock` in https://github.com/kotest/kotest-extensions-clock
Thanks

**Comment by sksamuel** [comment]
The mutable clock was only added as an internal implementation, and it was a mistake for us to make it public. The test clock repo is a better way to provide this.

**Pull request merged**
