### PR TITLE
Kotlin 1.7 compat test - replace `measureTime` with manual duration measure

### PR DESCRIPTION
**Pull request by aSemy**
Just a quick stab at fixing the issue here: https://github.com/kotest/kotest/issues/2960

This might help compatibility with 1.6 and 1.7

### CODE REVIEW

**Comment by jschneidereit** [comment]
Wow did they get rid of that function?

**Comment by aSemy** [comment]
> Wow did they get rid of that function?

No, they improved it: https://kotlinlang.org/docs/whatsnew17.html#time-marks-based-on-inline-classes-for-default-time-source

The issue is that internally it uses [`ValueTimeMark`](https://github.com/JetBrains/kotlin/blob/bcd8a28d4c77d1652ddcaaf0fdbe3524df2a2f05/libraries/stdlib/src/kotlin/time/TimeSource.kt#L54), which used to be a regular class - now it's a value class.

**Comment by sksamuel** [comment]
We need to do this for all places.
We use monotonic in continually, eventually, test case executor, constraits, until and logger.

**Comment by sksamuel** [comment]
@aSemy You can prob leave it in the tests because the tests will run with the same version of kotlin as we use in kotest.

**Comment by aSemy** [comment]
I tried re-implementing TimeMark. I got it working in Kotlin 1.7, but it's tricky because in Kotlin 1.6 it was an abstract class (now it's an interface)

* 1.6 https://github.com/JetBrains/kotlin/blob/ed3967eb585b63acdc7339726908bc0f2e6d8101/libraries/stdlib/src/kotlin/time/TimeSource.kt#L49
* 1.7 https://github.com/JetBrains/kotlin/blob/e4b2a8121b6a8bf6d2a5a3405053945b1ac9db68/libraries/stdlib/src/kotlin/time/TimeSource.kt#L78

I got up to `logger.kt` and then got a bit stuck, I'm not sure how to handle `writeLog(...)`

https://github.com/kotest/kotest/blob/33735bcd7571a41e4c6f328cac619c1e3563bdf2/kotest-common/src/commonMain/kotlin/io/kotest/mpp/logger.kt#L41

I'll commit what I have so far. If someone wants to take what I have and improve on it - please feel free!

**Comment by sksamuel** [comment]
That log thing is really just for kotest contributors to track bugs. Feel free to change it in any way you want. You can remove the timestamp entirely if you want.

**Comment by sksamuel** [comment]
Will be easier to merge this and continue in kotest repo.

**Pull request merged**
