### PR TITLE
Add String?.shouldBeInteger([Int]): Int

### PR DESCRIPTION
**Pull request by SerVB**
Hi! I frequently do something like
```kotlin
val int = str?.toIntOrNull()
int.shouldNotBeNull()

// work with int
```

So I've defined `shouldBeInteger` function in my project and now it's like
```kotlin
val int = str.shouldBeInteger()

// work with int
```
 
Is it OK to add this function to the repo?

### CODE REVIEW

**Comment by sksamuel** [comment]
Great idea, can we use contracts to smart case the type ?

**Comment by SerVB** [comment]
You mean a contract for non-null like the following?

```kotlin
@OptIn(ExperimentalContracts::class)
fun String?.shouldBeInteger(radix: Int = 10): Int {
    contract {
        returns() implies (this@shouldBeInteger != null)
    }

    return when (this) {
        null -> throw failure("String is null, but it should be integer.")

        else -> when (val integer = this.toIntOrNull(radix)) {
            null -> throw failure("String '$this' is not integer, but it should be.")

            else -> integer
        }
    }
}
```

It doesn't make much sense to me because after this operation I don't work with the initial string. However, if you think it could be useful, I can add it.

**Comment by sksamuel** [comment]
Not just null, but I wonder if we can use smart cast from string to int ?

a.shouldBeInt()
a % 3 shouldBe 1

**Comment by SerVB** [comment]
I think smart casting to `Int` is impossible here because there is still a `String` in `a` after this function returns.

But smart cast from `String?` to `String` is possible.

**Comment by sksamuel** [comment]
Ok makes sense

**Comment by SerVB** [comment]
Added the contract.

**Pull request merged**
