### PR TITLE
replace deprecated getTimeMillis with posix clock_gettime

### PR DESCRIPTION
**Pull request by aSemy**
`getTimeMillis()` is deprecated https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.system/get-time-millis.html

The alternative in this PR was discussed in Slack: https://slack-chats.kotlinlang.org/t/13154128/https-kotlinlang-org-api-latest-jvm-stdlib-kotlin-system-get

Part of #4085

### CODE REVIEW

**Comment by Kantis** [comment]
Did you consider removing `getTimeMillis` and using `measureTime` or `TimeSource.Monotonic.markNow()` as suggested in the docs for `getTimeMillis`?

**Comment by Kantis** [comment]
Ok, checked the surrounding code a bit and looks like this might be practical until we remove the old `continually` and `eventually` implementations.

**Review by Kantis — APPROVED** [review]

**Comment by aSemy** [comment]
Ah yes, good point, maybe we don't need `getTimeMillis()` at all.

I'll have a look...

**Comment by aSemy** [comment]
I think it'll make sense to remove `getTimeMillis()` in the same PR that removes the [TimeSource compatibility stuff](https://github.com/kotest/kotest/blob/0090ae49415fcae496a5cdaaacdc74c9a3118c59/kotest-common/src/commonMain/kotlin/io/kotest/common/timing.kt#L28).

I'll make another PR, and park this one for now...

**Comment by Kantis** [comment]
@aSemy I started doing those changes locally, but I think you need to do breaking changes in `eventually` and `continually` so not sure it's feasible to do before 6.0.

**Comment by aSemy** [comment]
Superseded by https://github.com/kotest/kotest/pull/4105

**Pull request closed without merging**
