### PR TITLE
Replace Range Intersect tests with Property Tests

### PR DESCRIPTION
**Pull request by AlexCue987**
add property testing for `intersect`, as suggested by @LeoColman

### CODE REVIEW

**Comment by LeoColman** [comment]
Cool!

**Review by LeoColman — APPROVED** [review]

**Comment by LeoColman** [comment]
You need to regenerate the binaries

**Comment by AlexCue987** [comment]
> You need to regenerate the binaries

did you mean run `apiDump`?

**Comment by AlexCue987** [comment]
> You need to regenerate the binaries

done

**Comment by LeoColman** [comment]
Yes, I meant API dump.
Called them binaries as they're the bytecode that we keep for binary compatibility

**Comment by LeoColman** [comment]
Nice one!
Thanks @AlexCue987 :)

**Comment by AlexCue987** [comment]
> Nice one! Thanks @AlexCue987 :)

no worries!

**Pull request merged**
