### PR TITLE
Replace timeout + timeUnit with Duration

### PR DESCRIPTION
**Pull request by helmbold**
The changelog style follows https://github.com/olivierlacan/keep-a-changelog . #29

### CODE REVIEW

**Comment by sksamuel** [comment]
Awesome. I might change the release version to 1.3 rather than 2.0 as that's still a major version. I know that's not strictly semver but it seems to be what most JVM projects do, eg Scala, Spark, Akka etc. What do you think?

**Comment by helmbold** [comment]
I think that many projects don't use versioning properly. The version numbers lose there expressiveness. And today version numbers are actually pretty cheap ;-) Let's follow semantic versioning.

Have you noticed that the build fails? I try to fix it (what is not optimal without beeing able to compile it under windows).

**Comment by sksamuel** [comment]
Yes I noticed, I will attempt a fix in a minute. I'm on windows atm and
need to reboot into linux.

**Comment by helmbold** [comment]
I tried to fix it and created another pull request. #31

**Comment by sksamuel** [comment]
Can't merge it - conflicts.

**Pull request merged**
