### PR TITLE
Convert inspectors to matchers/asserts

### PR DESCRIPTION
**Pull request by Kantis**
Inspectors could possibly be considered _just another assertion_ and be named using the regular `should...` syntax rather than `for..`.

Related issues: #2145 

#### Improved discoverability
When starting an assertion it feels like common practice to being with `subject should` and look for possible assertions. Inspectors will never show up when looking at the API this way

#### Erases the inspector concept
Inspectors become just another assertion. Less concepts to learn and a beginner will hopefully have an easy time picking up what these assertions do.

#### Changes an established concept
Old users will have to change habits and possibly migrate old code at some point. Aliases for the old inspector names could still be provided until Kotest 6.0 perhaps

### Suggested new names:
`forAll` -> `shouldAll`  -  asserts every element passes 
`forNone` -> `shouldContainNone` -  asserts no element passes (alternative name: `shouldNotContain`?)
`forOne` -> `shouldContainOne` -  asserts only a single element passed
`forAtMostOne` -> `shouldContainAtMostOne` -  asserts that either 0 or 1 elements pass
`forAtLeastOne` -> `shouldContainAtLeastOne` - asserts that 1 or more elements passed
`forAtLeast(k)` -> `shouldContainAtLeast(k)` -  asserts that k or more elements passed
`forAtMost(k)` -> `shouldContainAtMost(k)` -  asserts that k or fewer elements passed
`forAny` which is an alias for `forAtLeastOne`  ->  `shouldContainAtLeastOne`
`forSome` -> `shouldContainSome` - asserts that between 1 and n-1 elements passed. Ie, if NONE pass or ALL pass then we consider that a failure.
`forExactly(k)` -> `shouldContain(k)` - asserts that exactly _k_ elements pass

Examples:
```kotlin
val subjects = listOf(person(), person())
subjects.shouldAll {
  it.age shouldBeInRange 18..65
  it.name shouldBeIn listOf("hans", "greta")
}
```

I also tried making matchers out of the inspectors, to unify them with all other assertions.

Opening this PR to gather feedback on what people would feel about a change.

### CODE REVIEW

**Comment by sksamuel** [comment]
Personally I like the inspector naming because it just seems to read a lot nicer.

`subjects.forAtMostOne `

vs

`subjects.shouldContainAtMostOne` is pretty ugly to me.

forAll, forNone, forOne roll off the tongue much nicer than shouldAll, shouldContainNone, shouldContainOne.

But I can see the argument they are not as discoverable and probably not that many people use inspectors because of that.

**Comment by sksamuel** [comment]
For nomenclature, what about

`shouldForAll`
`shouldForOne`
`shouldForAtLeastOne`
`shouldForNone`

etc

**Comment by Kantis** [comment]
> For nomenclature, what about
> 
> `shouldForAll`
> `shouldForOne`
> `shouldForAtLeastOne`
> `shouldForNone`
> 
> etc

I think that's a great idea. Makes it a lot easier to migrate usages

**Comment by nilsschmidthamburg** [comment]
I totally agree on the point of discoverability. I my self discover(ed) 90% of the matchers by typing 'should' + autocomplete and look for the best fit. That's why I missed the inspectors like forAll, forAtLeastOne etc. in the first place. 

On the other hand, once I discovered inspectors, I love the way how these read at the moment. Look at this beauty:
`val subjects = listOf(person(), person())
subjects.forAtLeastOne { person ->
  person.age shouldBeInRange 18..65
}
`

In my personal opinion, I wouldn't be very happy with something along the lines of `shouldForAtLeastOne` as it doesn't read that well. I would rather prefer `shouldContainAtLeastOne`. The downside is that we would replace 3 letters (for) with 13 letters (shouldContain) in every single place.

To conclude, I would opt for `shouldContain....` as the new default, and deprecate the old `for...` versions. But I am happy to see more feedback from the community.

Looking at the PR, the only version I am not so sure about is `shouldAll`, but I couldn't come up with a better name so far :-/

**Comment by nilsschmidthamburg** [comment]
Regarding the PR, we should also adapt documentation in [documentation/docs/assertions/inspectors.md](https://github.com/kotest/kotest/blob/master/documentation/docs/assertions/inspectors.md)

**Comment by sksamuel** [comment]
I think our best idea so far is to add aliases as shouldXXX but then have the kotest intellij plugin suggest you rename to forXXX

**Pull request closed without merging**
