### PR TITLE
allow nested js tests

### PR DESCRIPTION
**Pull request by benkuly**

### CODE REVIEW

**Comment by benkuly** [comment]
Update:

It runs the tests without problems. I just have two issues with this solution and don't really know, how to fix them:
* `beforeSpec` and `afterSpec` seems to get ignored.
* The fail output doesn't make clear,  which subtest has failed.

**Comment by benkuly** [comment]
Please keep open for the case that someone could solve the two remaining issues.

**Comment by benkuly** [comment]
> Please keep open for the case that someone could solve the two remaining issues.

**Comment by benkuly** [comment]
Would be cool to find a solution, because many advantages of kotest disappear without support of nested test in all targets.

**Comment by aSemy** [comment]
Hi @benkuly, I've checked out your branch locally and updated it with the latest commits from the master branch, and I think it's working now. Could you please update your branch and check? If you can't, no worries, just let me know and I'll make a new PR.

**Comment by benkuly** [comment]
@aSemy feel free to open a new MR and close this. I just tried to update to upstream, but there were too many changes and it has been to long since I implemented it...

**Comment by benkuly** [comment]
see https://github.com/kotest/kotest/pull/3913

**Pull request closed without merging**
