### PR TITLE
Update junit_xml.md

### PR DESCRIPTION
**Pull request by obecker**
Fix: `JunitXmlReporter` is a `Listener`

### CODE REVIEW

**Comment by sksamuel** [comment]
Listeners are subsumed into extensions in 5.x

Are you running 4.x?

**Comment by obecker** [comment]
I'm using `io.kotest:kotest-extensions-htmlreporter:5.2.3`.
In my IDE I'm seeing `HtmlReporter` extends `ProjectListener`, which extends `BeforeProjectListener` and `AfterProjectListener`, and both extend `Listener`.
I got a compile error because `HtmlReporter` was not an `Extension` ...

**Comment by obecker** [comment]
Ah, I got it. I have `io.kotest:kotest-framework-api-jvm:4.6.4` in my classpath. Sorry, my fault.

**Comment by sksamuel** [comment]
You should be using 5.2.3 framework, and then the docs are current.
Does that not work for you ?

**Comment by sksamuel** [comment]
Ok glad you got it sorted :)

**Pull request closed without merging**
