### PR TITLE
#2845 Matcher compose

### PR DESCRIPTION
**Pull request by pientaa**
Implements #2845 

Before I finish PR, I'd like to make sure if that's what you meant @sksamuel in that issue

### CODE REVIEW

**Comment by sksamuel** [comment]
Yes you're on the right lines. I don't think you need the fold though, could just do .all { matcher -> ... }

**Comment by kierans** [comment]
Just wondering if there's any documentation that should be added so that new people can learn of this feature?

**Comment by sksamuel** [comment]
I will rework the custom matchers documentation today since it is lacking in so many places anyway.

**Comment by sksamuel** [comment]
Ok much better custom matcher docs are now up.

**Pull request merged**
