### PR TITLE
Replace Kotlintest with Kotest

### PR DESCRIPTION
**Pull request by LeoColman**

### CODE REVIEW

**Comment by LeoColman** [comment]
Ok, so this is the first PR for the migration of `kotlintest` to `kotest`.

I replaced all instances of `kotlintest` with `kotest`, except for anything in the documentation.

I know it's impossible to check file by file, but I don't have a clue on what we can do to ensure this is right (A lot of replacing and refactoring done in IntelliJ)

**Comment by Kerooker** [comment]
I might have hit replace all by mistake, reverting now

**Comment by BorzdeG** [comment]
But why?

**Comment by sksamuel** [comment]
@BorzdeG https://github.com/kotlintest/kotlintest/issues/948

**Comment by sksamuel** [comment]
@Kerooker can you fix the conflicts?

**Comment by LeoColman** [comment]
Sure

**Comment by LeoColman** [comment]
@sksamuel This is probably good to go

**Comment by sksamuel** [comment]
More conflicts.
Once these are fixed, can you make sure there are no other oustanding PRs from other contributors (except docs) and then merge?

**Comment by LeoColman** [comment]
I merged master again.
I think we'll take the risk and merge this. It's getting dangerous to merge new features all the time, as we might delete something by accident.

I checked that the latest 15 commits or so to master are all OK in this PR, so I believe it will work, but we'll have to watch if anything was lost.

**Pull request merged**
