### PR TITLE
#2741 Not work `js{}` and `js(BOTH){}` - only `js(IR) {}`

### PR DESCRIPTION
**Pull request by BorzdeG**
#2741 

* Updated Gradle version
* Updated Kotlin version
* Added support Legacy JS backend

### CODE REVIEW

**Comment by sksamuel** [comment]
The framework modules uses a compiler plugin for JS - have you tested that it works for legacy?

**Comment by BorzdeG** [comment]
yes, I local run `./gradlew ﻿﻿jsIrTest jsLegacyTest` in MacOS

GitHub Actions (examples in Ubuntu): [jsIrTest](https://github.com/kotest/kotest/runs/4575649207?check_suite_focus=true#step:4:442) , [jsLegacyTest](https://github.com/kotest/kotest/runs/4575649207?check_suite_focus=true#step:4:712)

I only crash ConcurrentTestsSingleInstanceTest - it takes longer than expected: "2717 should be <1499"
But I don't think it is related to IR - the test is for jvm, not js

**Comment by sksamuel** [comment]
We need to test this against the `kotest-tests-js` module which actually executes javascript tests using the compiler plugin. I'm not sure how this can work given the compiler plugin uses IR classes.

**Comment by BorzdeG** [comment]
Did I understand correctly - now there are no tests for him and it is necessary to supplement the PR with these tests?

**Comment by sksamuel** [comment]
No, we just have to make sure that the tests in `kotest-tests/kotest-tests-js` work and are being detected.
We should build locally using these changes and use that version of the compiler plugin in that project to test.
Like I mentioned in the other issue, I don't see how this can work given the compiler plugin uses IR classes.

**Pull request closed without merging**
