### PR TITLE
Alex/similar strings (#4456)

### PR DESCRIPTION
**Pull request by AlexCue987**
if an exact match for a string is not found, search for similar strings, such as:

```kotlin
            val message = shouldThrow<AssertionError> {
               listOf("sweet green apple", "sweet red apple").shouldContainExactlyInAnyOrder(
                  listOf(
                     "sweet green apple",
                     "sweet red plum",
                  )
               )
            }.message
            println(message)
            message.shouldContainInOrder(
               "Possible matches for unexpected elements:",
               """expected: <"sweet red plum">, found a similar value: <"sweet red apple">""",
               """Line[0] ="sweet red apple"""",
               """Match[0]= ++++++++++-----""",
            )
```

### CODE REVIEW

**Review by LeoColman — COMMENTED** [review]
this one is a chonker

**Comment by AlexCue987** [comment]
> this one is a chonker

yeah

**Comment by AlexCue987** [comment]
> this one is a chonker

TBH I can't see a way to make it smaller. Sorry about that.

**Comment by AlexCue987** [comment]
too many conflicts, will resubmit later

**Pull request closed without merging**
