### PR TITLE
shouldBeEqualToUsingFields shouldBeEqualToIgnoringFields #711

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Comment by sksamuel** [comment]
@AlexBroadbent please review

**Comment by AlexBroadbent** [comment]
Looks great to me - thanks!

**Review by AlexBroadbent — APPROVED** [review]

**Review by LeoColman — APPROVED** [review]

**Comment by LeoColman** [comment]
Just missing some javadocs. I can add them if you want.

I like writing docs :P

**Comment by sksamuel** [comment]
Be my guest.

**Comment by LeoColman** [comment]
Should I add the docs to `matchers.md` already?

**Pull request merged**
