### PR TITLE
Issue #3099 fix tolerance matchers to support edge-case numeric inputs

### LINKED ISSUE #3099: Tolerance matchers fail on edge-case numeric inputs
While working on #3096, the property-based checker found some edge cases for tolerance matchers which don't appear to work correctly (or at least have somewhat strange behavior).

Cases where we should probably throw an `IllegalArgumentException`: 

```kotlin
(Float.NaN).shouldBeWithinPercentageOf(Float.NaN, 1.0)         // => NaN should be in NaN..NaN
(Double.NaN).shouldBeWithinPercentageOf(Double.NaN, 1.0)       // => NaN should be in NaN..NaN
0.shouldBeWithinPercentageOf(0, Double.POSITIVE_INFINITY)      // => 0 should be in NaN..NaN
0L.shouldBeWithinPercentageOf(0L, Double.POSITIVE_INFINITY)    // => 0 should be in NaN..NaN
0f.shouldBeWithinPercentageOf(0f, Double.POSITIVE_INFINITY)    // => 0.0 should be in NaN..NaN
0.0.shouldBeWithinPercentageOf(0.0, Double.POSITIVE_INFINITY)  // => 0.0 should be in NaN..NaN
```

Cases where behavior differs from `x shouldBe (y plusOrMinus z.percent)`:

```kotlin
// Applies to both Double and Float

NEGATIVE_INFINITY shouldBe (NEGATIVE_INFINITY plusOrMinus 1.percent) // OK
POSITIVE_INFINITY shouldBe (POSITIVE_INFINITY plusOrMinus 1.percent) // OK

NEGATIVE_INFINITY.shouldBeWithinPercentageOf(NEGATIVE_INFINITY, 1.0) // -Infinity should be in -Infinity..NaN
POSITIVE_INFINITY.shouldBeWithinPercentageOf(POSITIVE_INFINITY, 1.0) // Infinity should be in NaN..Infinity
```

**Which version of Kotest are you using**
#3096 - branched from 56573a7

### PR DESCRIPTION
**Pull request by tomekoleksy**
Fixes #3099

### CODE REVIEW

**Review by LeoColman — APPROVED** [review]

**Comment by LeoColman** [comment]
LGTM!

**Comment by LeoColman** [comment]
I disabled automerge as #3240 is also a solution to the same issue.
@sksamuel @piotrb5e3 @tomekoleksy What do you think? If needed we can bring this discussion to our KotlinLang Slack Channel

**Comment by sksamuel** [comment]
> I disabled automerge as #3240 is also a solution to the same issue. @sksamuel @piotrb5e3 @tomekoleksy What do you think? If needed we can bring this discussion to our KotlinLang Slack Channel

I have no opinion on which to merge. Let's let the authors decide which solution they think is best. @tomekoleksy @piotrb5e3

**Comment by tomekoleksy** [comment]
I prefer solution implemented by @piotrb5e3. It's more generic and in easier way cover all differences between those two operators.

**Pull request closed without merging**
