### PR TITLE
Reworked dsl to share scopes

### PR DESCRIPTION
**Pull request by sksamuel**

### CODE REVIEW

**Comment by crazyk2** [comment]
Which problem did you solve?

**Comment by sksamuel** [comment]
There is a bug in intellij which caused it to get into a loop when
highlighting the files in MPP mode. This avoids that bug.

**Comment by crazyk2** [comment]
Could you share link (bug or discussion of problem)?

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/issues/5511

**Pull request merged**
