### PR TITLE
Fix flaky tests ContinuallySpec, EventuallySpec

### PR DESCRIPTION
**Pull request by OliverO2**
Fix tests:
* Make ContinuallySpec tolerate test duration >= 1s
* Make EventuallySpec use virtual time

### CODE REVIEW

**Review by aSemy — APPROVED** [review]

**Comment by aSemy** [comment]
Looks like the merge queue is failing with an unrelated flakey error (caused by #https://github.com/kotest/kotest/pull/4119?), so I'll go ahead and directly merge.


```
com.sksamuel.kotest.runner.junit5.DiscoveryTestWithSelectors[jvm]
  Test discovery should support multiple package selectors[jvm] FAILED (6.9s)
  io.kotest.engine.config.ConfigurationException: io.kotest.engine.config.ConfigurationException: io.github.classgraph.ClassGraphException: Uncaught exception during scan
  Caused by: io.kotest.engine.config.ConfigurationException: io.github.classgraph.ClassGraphException: Uncaught exception during scan
  Caused by: io.github.classgraph.ClassGraphException: Uncaught exception during scan
  Caused by: java.lang.OutOfMemoryError: Java heap space
```


I created a follow-up to improve Kotest classpath scanning https://github.com/kotest/kotest/issues/4144

**Comment by aSemy** [comment]
> * Make EventuallySpec use virtual time

I've already merged so this question is too late, but I don't think this PR enables virtual time for `eventually`?

I see the PR sets `coroutineTestScope = true`, but it doesn't set a time source like in the other `eventually` test:

https://github.com/kotest/kotest/blob/f1c11fce62c41e53fc0f982c22d3375f712b7c73/kotest-assertions/kotest-assertions-core/src/jvmTest/kotlin/io/kotest/assertions/nondeterministic/EventuallyTest.kt#L459

**Comment by OliverO2** [comment]
I'm preparing a PR to address the issue, so that the time source used in tests is always synchronized with the scheduler in use.

**Comment by OliverO2** [comment]
OK, got that little thing here: https://github.com/kotest/kotest/pull/4149

**Pull request merged**
