### PR TITLE
Add support for Linux ARM64 and macOS ARM64 (Silicon) targets.

### PR DESCRIPTION
**Pull request by charleskorn**
Currently blocked until a new version of kotlinx.coroutines is published with these targets (see https://github.com/Kotlin/kotlinx.coroutines/pull/2904).

See https://github.com/kotest/kotest/issues/1743#issuecomment-909207911.

### CODE REVIEW

**Comment by JavierSegoviaCordoba** [comment]
Can you add the new Apple simulator targets too (ios tvos and watchos)?

**Comment by charleskorn** [comment]
> Can you add the new Apple simulator targets too (ios tvos and watchos)?

Done.

**Comment by charleskorn** [comment]
Looks like #2450 broke some tests - could you take a look @sksamuel?

**Comment by JavierSegoviaCordoba** [comment]
Coroutines 1.5.2 and mt are available.

**Comment by sksamuel** [comment]
I hope 1.5.2 fixes my issue with Result cast exceptions :)

**Comment by sksamuel** [comment]
> Looks like #2450 broke some tests - could you take a look @sksamuel?

Yep

**Comment by charleskorn** [comment]
This is ready for review @sksamuel.

**Comment by sksamuel** [comment]
Awesome 👍🏼

**Comment by sksamuel** [comment]
Don't know if this error means anything to you @charleskorn https://github.com/kotest/kotest/runs/3507598103?check_suite_focus=true

**Comment by JavierSegoviaCordoba** [comment]
Not sure if `kotlin.native.enableDependencyPropagation=false` in `gradle.properties` can fix that

**Comment by JavierSegoviaCordoba** [comment]
@sksamuel linuxArm64 isn't in kotlin coroutines:

```
        addTarget(presets.linuxX64)
        addTarget(presets.iosArm64)
        addTarget(presets.iosArm32)
        addTarget(presets.iosX64)
        addTarget(presets.macosX64)
        addTarget(presets.mingwX64)
        addTarget(presets.tvosArm64)
        addTarget(presets.tvosX64)
        addTarget(presets.watchosArm32)
        addTarget(presets.watchosArm64)
        addTarget(presets.watchosX86)
        addTarget(presets.watchosX64)
        addTarget(presets.iosSimulatorArm64)
        addTarget(presets.watchosSimulatorArm64)
        addTarget(presets.tvosSimulatorArm64)
        addTarget(presets.macosArm64)
```

**Comment by sksamuel** [comment]
The PR passed. I guess the PR workflow wasn't updated the same as the master workflow.

**Comment by JavierSegoviaCordoba** [comment]
we should ask in coroutines for this target, but it is strange it doesn't exist yet

**Comment by JavierSegoviaCordoba** [comment]
https://github.com/Kotlin/kotlinx.coroutines/issues/855

**Comment by charleskorn** [comment]
> Don't know if this error means anything to you @charleskorn https://github.com/kotest/kotest/runs/3507598103?check_suite_focus=true

Yep, that would be because kotlinx.coroutines doesn't support `linuxArm64`. 

> The PR passed. I guess the PR workflow wasn't updated the same as the master workflow.

[The Linux PR workflow runs `check`](https://github.com/kotest/kotest/pull/2449/files#diff-db41ffe2c658df28e2cc8e19c303f1b0942d56b6fb1b0fedc2dc3b916e005b00R28), which should run everything that can be run on Linux (including building Linux ARM64 targets but not testing them), not sure why it didn't pick this up. 

> we should ask in coroutines for this target, but it is strange it doesn't exist yet

Sounds great, thanks for doing that.

In the meantime, do you want me to remove the `linuxArm64` targets?

**Comment by sksamuel** [comment]
I think we should remove them for now yeah.

**Comment by charleskorn** [comment]
I've opened #2460 to remove the Linux ARM64 target.

**Comment by JavierSegoviaCordoba** [comment]
I created it too, but I forgot to modify the workflows, I will close it

**Pull request merged**
