### PR TITLE
Feature/3382

### PR DESCRIPTION
**Pull request by lgtout**
This is a draft PR showing work done for 13-arity, and part of 14-arity.  
Please let me know if it looks okay.  If so, I'll replicate  for the remaining arities.  
Thanks!

### CODE REVIEW

**Comment by vlsi** [comment]
Is this code generated?
Can it rather be replaced with a single method that takes List of arguments?

The current PR is really impossible to review and test

**Comment by lgtout** [comment]
@vlsi It's a draft PR.  See [this](https://kotlinlang.slack.com/archives/CT0G9SD7Z/p1675546893648889) conversation in Slack.  It was written by hand, not generated.  What do you mean that it's impossible to review and test?  It's incomplete.  As per the Slack convo, it was just to get @sksamuel's feedback before moving on to the bulk of the work.

**Comment by vlsi** [comment]
Have you considered adding a single vararg or List method instead?

What is the purpose of copy-pasting the repeated code for all the arities?

**Comment by lgtout** [comment]
@vlsi That's something you should discuss with @sksamuel.  As per the Slack convo, this was the approach he asked for.  I'm agnostic to implementation.

**Comment by vlsi** [comment]
Ah, vararg / List won't handle `property` arguments.

In that case, it would be nice to have the code generated to avoid off-by-one errors

**Comment by lgtout** [comment]
If you propose a way to generate the code, and @sksamuel approves, I'll consider implementing it, depending on how much time I have available, and compared with how much time completing the manual approach will take.

**Review by sksamuel — APPROVED** [review]

**Pull request merged**
