### PR TITLE
Fix mapcontain (#55)

### LINKED ISSUE #3959: `shouldContain` always matches against `null` map value
kotest 5.8.1

The following succeeds when it should fail:
```kotlin
mapOf("foo" to "bar") shouldContain ("baz" to null)
```

due to https://github.com/kotest/kotest/blob/92091b869f3a8649cb9f6eed292222a0cd899cab/kotest-assertions/kotest-assertions-core/src/commonMain/kotlin/io/kotest/matchers/maps/matchers.kt#L10

### PR DESCRIPTION
**Pull request by AlexCue987**
* fix [issue with mapcontain](https://github.com/kotest/kotest/issues/3959)
* clean up the following function that has an exact duplicate:

```
fun <K, V> contain(key: K, v: V): Matcher<Map<K, V>> = object : Matcher<Map<K, V>> {
   override fun test(value: Map<K, V>) = MatcherResult(
      value[key] == v,
      { "Map should contain mapping $key=$v but was ${buildActualValue(value)}" },
      { "Map should not contain mapping $key=$v but was $value" }
   )

   private fun buildActualValue(map: Map<K, V>) = map[key]?.let { "$key=$it" } ?: map
}
```

### CODE REVIEW

**Comment by sksamuel** [comment]
@AlexCue987 can you fix the test ?

**Comment by Kantis** [comment]
Looks like some other tests relied on the output of the matcher. Other than that I think it looks good to merge

**Review by sksamuel — APPROVED** [review]

**Comment by sksamuel** [comment]
Looks like tests are still failing

**Comment by sksamuel** [comment]
I wasn't sure how to fix the conflicts @AlexCue987

**Comment by AlexCue987** [comment]
trying to resolve issues with PGP keys, reopened off of another branch https://github.com/kotest/kotest/pull/4214

can you pls review @sksamuel

**Pull request closed without merging**
