### PR TITLE
Print project configurations (#841)

### LINKED ISSUE #841: Add print statement for config
To make it clear project config was discovered

### PR DESCRIPTION
**Pull request by faogustavo**
Closes #841

---

## Testing Command:
```
./gradlew :kotlintest-tests:kotlintest-tests-core:test
```

## Evidence:
image

### CODE REVIEW

**Comment by sksamuel** [comment]
Great!

Parallelism is spelled wrong.
Also theses should this.

**Comment by faogustavo** [comment]
Done!

**Comment by sksamuel** [comment]
Happy to merge, but need to fix this failing test first:

```Gradle Test Executor 4 STANDARD_ERROR
    java.lang.IllegalStateException: it::class.java.canonicalName must not be null
    	at io.kotlintest.Project.printConfigs(Project.kt:135)
    	at io.kotlintest.Project.beforeAll(Project.kt:94)
    	at io.kotlintest.runner.jvm.TestEngine.start(TestEngine.kt:38)
    	at io.kotlintest.runner.jvm.TestEngine.execute(TestEngine.kt:73)
    	at io.kotlintest.runner.junit5.KotlinTestEngine.execute(KotlinTestEngine.kt:43)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
    	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
    	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
```

**Comment by sksamuel** [comment]
Great stuff

**Pull request merged**
