### PR TITLE
(#889) add LocalTime asserts

### PR DESCRIPTION
**Pull request by alladywek**

### CODE REVIEW

**Review by sksamuel — COMMENTED** [review]
Should we add haveSeconds haveMinutes etc. I can't remember if I had added them in the past.

**Comment by LeoColman** [comment]
I think we should, as LocalTimes are made for this kind of glanularity

**Comment by LeoColman** [comment]
But `time.minutes shouldBe 12` isn't that hard to type either. It wouldn't hurt to add though

**Comment by sksamuel** [comment]
True

**Comment by sksamuel** [comment]
Yeah time.minutes shouldBe 12 is fine.
Merging this.

**Pull request merged**
