### PR TITLE
[#933] Renamed from `...ExactlyInAnyOrder` to `...AllInAnyOrder`.

### PR DESCRIPTION
**Pull request by atmikev**

### CODE REVIEW

**Comment by atmikev** [comment]
Forgot that I needed to deprecate the old method names. Closing and will update then reopen.

**Review by LeoColman — APPROVED** [review]

**Comment by LeoColman** [comment]
Could you please fix the compilation errors?

**Comment by atmikev** [comment]
@Kerooker @sksamuel  all fixed!

**Comment by LeoColman** [comment]
I believe this guy is mentioned somewhere in the documentation. It would be wise to update there as well, what do you think?

**Pull request merged**
